import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const appDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(appDir, '../..')
const notebookAppSource = readFileSync(join(appDir, './NotebookApp.tsx'), 'utf8')
const appCssSource = readFileSync(join(appDir, '../App.css'), 'utf8')
const iconSource = readFileSync(join(appDir, '../icons/app-icons.ts'), 'utf8')
const electronApiSource = readFileSync(join(repoRoot, 'src/types/electron-api.d.ts'), 'utf8')
const preloadSource = readFileSync(join(repoRoot, 'electron/preload.cjs'), 'utf8')
const ipcStorageSource = readFileSync(join(repoRoot, 'electron/ipc-storage.mjs'), 'utf8')

describe('notebook sidebar tree', () => {
  it('renders a file-tree style sidebar without data transfer actions', () => {
    expect(notebookAppSource).toContain("const folderIconId = isFolder && !collapsed && children.length > 0 ? 'folderOpen' : 'folder'")
    expect(notebookAppSource).toContain('className="notebook-tree-folder-icon"')
    expect(notebookAppSource).not.toContain("'chevronRight'")
    expect(notebookAppSource).not.toContain("'chevronDown'")
    expect(notebookAppSource).not.toContain("'fileText'")
    expect(notebookAppSource).toContain('notebook-tree-children')
    expect(notebookAppSource).toContain("onSelectFolder={selectSidebarTreeFolder}")
    expect(notebookAppSource).toContain('className="notebook-sidebar-header" aria-label="Notebook actions"')
    expect(notebookAppSource).toContain('iconId="filePlus"')
    expect(notebookAppSource).toContain('iconId="folderPlus"')
    expect(notebookAppSource).not.toContain('<h1>Notebook</h1>')
    expect(notebookAppSource).not.toContain('<button type="button" onClick={createNote}>New note</button>')
    expect(notebookAppSource).not.toContain('<button type="button" onClick={createFolder}>New folder</button>')
    expect(notebookAppSource).not.toContain('notebook-sidebar-actions')
    expect(notebookAppSource).not.toContain('notebook-utility-nav')
    expect(appCssSource).not.toContain('.notebook-sidebar-actions')
    expect(appCssSource).not.toContain('.notebook-utility-nav')
    expect(notebookAppSource).not.toContain('<button type="button" onClick={importNotebook}>Import</button>')
    expect(notebookAppSource).not.toContain('<button type="button" onClick={exportNotebook}>Export</button>')
  })

  it('uses soft note-only tree selection instead of persistent folder highlighting', () => {
    expect(appCssSource).toContain('.notebook-tree-row.is-note.is-active .notebook-tree-main')
    expect(appCssSource).not.toContain('.notebook-tree-row.is-active .notebook-tree-main')
    expect(notebookAppSource).toContain("const active = item.type === 'note' && item.id === activeNoteId")
    expect(notebookAppSource).toContain("const selected = item.type === 'note' && selectedNoteIds.has(item.id)")
    expect(appCssSource).toContain('--notebook-tree-row-bg: color-mix(in srgb, var(--app-text) 10%, transparent);')
    expect(appCssSource).toContain('.notebook-tree-children::before')
    expect(appCssSource).toContain('padding: 4px 8px 4px calc(var(--tree-depth, 0) * 12px + 5px);')
    expect(appCssSource).toContain('padding-left: calc(var(--tree-depth, 0) * 12px + 5px);')
    expect(appCssSource).toContain('.notebook-tree-children .notebook-tree-row.is-note .notebook-tree-main')
    expect(appCssSource).toContain('padding-left: calc(var(--tree-depth, 0) * 12px + 11px);')
    expect(appCssSource).toContain('left: calc(var(--tree-depth, 0) * 12px + 13px);')
    expect(appCssSource).toContain('--notebook-tree-row-bg: transparent;')
    expect(appCssSource).toContain('background: var(--notebook-tree-row-bg);')
    expect(appCssSource).toContain('.notebook-tree-folder-icon')
    expect(appCssSource).toContain('height: 22px;')
    expect(appCssSource).toContain('linear-gradient(var(--notebook-tree-row-bg), var(--notebook-tree-row-bg))')
    expect(appCssSource).not.toContain('.notebook-tree-row.is-active .notebook-tree-main,\n.notebook-search-result.is-active')
  })

  it('supports intentional long-press rename and sidebar drag/drop reordering', () => {
    expect(notebookAppSource).toContain('NOTEBOOK_TREE_RENAME_LONG_PRESS_MS = 500')
    expect(notebookAppSource).toContain('onPointerDown={beginLongPressRename}')
    expect(notebookAppSource).toContain('className="notebook-tree-rename-input"')
    expect(notebookAppSource).toContain("type NotebookTreeRenameCommitSource = 'enter' | 'blur' | 'tab'")
    expect(notebookAppSource).toContain("onBlur={() => onCommitRename('blur')}")
    expect(notebookAppSource).toContain("onCommitRename('enter')")
    expect(notebookAppSource).toContain("event.key === 'Tab' && !event.shiftKey && tabCreatesNext")
    expect(notebookAppSource).toContain("onCommitRename('tab')")
    expect(notebookAppSource).toContain('draggable={!renaming}')
    expect(notebookAppSource).toContain('moveNotebookItems(previous.notebook, draggedNoteIds, target.parentFolderId, target.index)')
    expect(notebookAppSource).toContain('moveNotebookItem(previous.notebook, draggedItemId, target.parentFolderId, target.index)')
    expect(notebookAppSource).toContain('notebook-tree-root-drop-zone')
    expect(appCssSource).toContain('.notebook-tree-row.is-drop-before::before')
    expect(appCssSource).toContain('.notebook-tree-row.is-drop-inside .notebook-tree-main')
    expect(appCssSource).toContain('.notebook-tree-root-drop-zone.is-drop-root')
  })

  it('supports note-only multi-selection with shift and command click', () => {
    expect(notebookAppSource).toContain("type NotebookTreeNoteSelectionMode = 'replace' | 'toggle' | 'range'")
    expect(notebookAppSource).toContain('aria-multiselectable="true"')
    expect(notebookAppSource).toContain('getVisibleNotebookTreeNoteIds(state.notebook.items, collapsedFolderIds)')
    expect(notebookAppSource).toContain('getNotebookTreeRangeNoteIds(visibleTreeNoteIds, anchorNoteId, noteId)')
    expect(notebookAppSource).toContain("event.shiftKey ? 'range' : event.metaKey || event.ctrlKey ? 'toggle' : 'replace'")
    expect(notebookAppSource).toContain('setSelectedTreeNoteIds([])')
    expect(notebookAppSource).toContain('draggingNoteIds.has(item.id)')
    expect(appCssSource).toContain('.notebook-tree-row.is-note.is-selected .notebook-tree-main')
  })

  it('does not keep hidden inline rename or delete controls in note rows', () => {
    expect(notebookAppSource).not.toContain('notebook-tree-actions')
    expect(notebookAppSource).not.toContain('notebook-tree-action')
    expect(appCssSource).not.toContain('notebook-tree-actions')
    expect(appCssSource).not.toContain('notebook-tree-action')
    expect(notebookAppSource).not.toContain('onDoubleClick={() => onStartRename(item.id, item.title)}')
    expect(appCssSource).toContain('max-width: 100%;')
    expect(appCssSource).toContain('box-sizing: border-box;')
  })

  it('wires sidebar note activation to notebook cursor restore', () => {
    expect(notebookAppSource).toContain('externalStateLoadVersion')
    expect(notebookAppSource).toContain('externalStateLoadVersion, commitAppStateNow } = usePersistentAppState()')
    expect(notebookAppSource).toContain('externalStateLoadVersion,')
    expect(notebookAppSource).toContain('useNoteCursorPersistence')
    expect(notebookAppSource).toContain('usePendingNoteCursorRestore')
    expect(notebookAppSource).toContain('useNotebookNavigationHistory')
    expect(notebookAppSource).toContain('resolveNotebookNavigationLocation(snapshotState, location)')
    expect(notebookAppSource).toContain('applyNotebookNavigationLocation({ noteId, aisleId: \'\' })')
    expect(notebookAppSource).toContain('const snapshots = notebookEditors.getMountedEditorMarkdownSnapshots()')
    expect(notebookAppSource).toContain('const previousWithEditorContent = applyNotebookEditorMarkdownSnapshotsToState(previous, snapshots)')
    expect(notebookAppSource).toContain('const previousWithCursor = applyActiveCursorToState(previousWithEditorContent)')
    expect(notebookAppSource).toContain('pendingFocusToAisleIdRef.current = resolvedLocation.aisleId || null')
    expect(notebookAppSource).toContain('if (pendingFocusToAisleIdRef.current !== (resolvedLocation.aisleId || null)) return')
    expect(notebookAppSource).toContain('activateAisleEditor(buildAisleEditorKey(active.noteBody.id, resolvedLocation.aisleId), {')
    expect(notebookAppSource).toContain("source: 'programmatic'")
  })

  it('lets workspace pointer activation cancel pending cursor restore before focusing an aisle', () => {
    expect(notebookAppSource).toContain('shouldClearPendingCursorRestoreForAisleActivation')
    expect(notebookAppSource).toContain('onActivateAisle={(editorKey, pointer) => {')
    expect(notebookAppSource).toContain('pendingCursorRestoreRef.current = null')
    expect(notebookAppSource).toContain('pendingFocusToAisleIdRef.current = null')
    expect(notebookAppSource).toContain('focusAtClientPoint: pointer')
    expect(notebookAppSource).toContain("source: 'pointer'")
  })

  it('starts newly created notes and folders in inline rename after revealing the sidebar tree', () => {
    expect(notebookAppSource).toContain('function clearSidebarSearchFilter(currentFilter: NoteFilterSettings | null | undefined): NoteFilterSettings')
    expect(notebookAppSource).toContain('function revealNotebookTreeForCreatedItem(')
    expect(notebookAppSource).toContain('sidebarCollapsed: false')
    expect(notebookAppSource).toContain('noteFilter: clearSidebarSearchFilter(ui.noteFilter)')
    expect(notebookAppSource).toContain('const createdRenameRef: { current: PendingCreatedTreeRename | null } = { current: null }')
    expect(notebookAppSource).toContain("createdRenameRef.current = {\n        kind: 'note',\n        itemId: result.noteId,")
    expect(notebookAppSource).toContain("createdRenameRef.current = {\n        kind: 'folder',\n        itemId: result.folderId,")
    expect(notebookAppSource).toContain('ui: revealNotebookTreeForCreatedItem(result.state.ui, [parentFolderId])')
    expect(notebookAppSource).toContain('ui: revealNotebookTreeForCreatedItem(result.state.ui, [parentFolderId, result.folderId])')
    expect(notebookAppSource).toContain("beginCreatedTreeRename(createdRename, 'Untitled')")
    expect(notebookAppSource).toContain("beginCreatedTreeRename(createdRename, 'Untitled folder')")
  })

  it('routes post-create rename focus only from Enter commits', () => {
    expect(notebookAppSource).toContain('const pendingCreatedTreeRenameRef = useRef<PendingCreatedTreeRename | null>(null)')
    expect(notebookAppSource).toContain('pendingCreatedEditRef.current = pending')
    expect(notebookAppSource).toContain("if (source !== 'enter') return")
    expect(notebookAppSource).toContain('pendingFocusToAisleIdRef.current = pending.aisleId')
    expect(notebookAppSource).toContain('pendingScrollToAisleIdRef.current = pending.aisleId')
    expect(notebookAppSource).toContain('pendingNavigationTopAisleIdRef.current = pending.aisleId')
    expect(notebookAppSource).toContain("focusIntent: 'aisle-activation'")
    expect(notebookAppSource).toContain("const returnNoteBodyId = activeModel?.noteBody.id ?? ''")
    expect(notebookAppSource).toContain('const returnAisleId = renderedActiveAisleId')
    expect(notebookAppSource).toContain('notebookEditors.activateAisleEditor(buildAisleEditorKey(pending.returnNoteBodyId, pending.returnAisleId), {')
    expect(notebookAppSource).toContain('focus: true')
    expect(notebookAppSource).toContain("source: 'programmatic'")
    expect(notebookAppSource).toContain('finishCreatedTreeRename(renamingTreeItemId, source)')
  })

  it('uses Tab during created item rename to create the next sibling of the same type', () => {
    expect(notebookAppSource).toContain('const skipTreeRenameBlurItemIdRef = useRef(\'\')')
    expect(notebookAppSource).toContain('createdRenameItemId={pendingCreatedTreeRenameRef.current?.itemId ?? \'\'}')
    expect(notebookAppSource).toContain('const tabCreatesNext = item.id === createdRenameItemId')
    expect(notebookAppSource).toContain("if (source === 'tab' && pendingCreatedRename) {")
    expect(notebookAppSource).toContain('const entry = findNotebookItem(stateRef.current.notebook.items, pendingCreatedRename.itemId)')
    expect(notebookAppSource).toContain('createNoteAt(entry.parentFolderId, entry.index + 1)')
    expect(notebookAppSource).toContain('createFolderAt(entry.parentFolderId, entry.index + 1)')
    expect(notebookAppSource).toContain("if (source === 'blur' && skipTreeRenameBlurItemIdRef.current === renamingTreeItemId)")
  })

  it('wires note and folder sidebar context menus with reveal, rename, and delete actions', () => {
    expect(notebookAppSource).toContain('function NotebookTreeContextMenu')
    expect(notebookAppSource).toContain('getNotebookSidebarRevealLabel')
    expect(notebookAppSource).toContain('onCreateNote: () => void')
    expect(notebookAppSource).toContain('onCreateFolder: () => void')
    expect(notebookAppSource).toContain("const getTreeContextCreateTarget = useCallback((): { parentFolderId: string | null; index: number } | null => {")
    expect(notebookAppSource).toContain("if (entry.item.type === 'folder') {")
    expect(notebookAppSource).toContain('parentFolderId: entry.item.id')
    expect(notebookAppSource).toContain('index: entry.item.children.length')
    expect(notebookAppSource).toContain('parentFolderId: entry.parentFolderId')
    expect(notebookAppSource).toContain('index: entry.index + 1')
    expect(notebookAppSource).toContain('createNoteAt(target.parentFolderId, target.index)')
    expect(notebookAppSource).toContain('createFolderAt(target.parentFolderId, target.index)')
    expect(notebookAppSource).toContain('New note')
    expect(notebookAppSource).toContain('New folder')
    expect(notebookAppSource).toContain('Reveal in Finder')
    expect(notebookAppSource).toContain('Show in File Explorer')
    expect(notebookAppSource).toContain("const deleteLabel = menu.itemType === 'folder' ? 'Delete folder' : 'Delete note'")
    expect(notebookAppSource).toContain('onContextMenu={(event) => {')
    expect(notebookAppSource).toContain('revealNotebookItemLocation(payload)')
    expect(notebookAppSource).toContain("trigger: 'notebook-sidebar-reveal-item'")
    expect(notebookAppSource).toContain('const latest = getLatestNotebookStateFromMountedEditors()')
    expect(notebookAppSource).toContain('pendingEditorCount: latest.pendingEditorCount')
    expect(notebookAppSource.indexOf('New note')).toBeLessThan(notebookAppSource.indexOf('New folder'))
    expect(notebookAppSource.indexOf('New folder')).toBeLessThan(notebookAppSource.indexOf('Rename'))
    expect(notebookAppSource.indexOf('Rename')).toBeLessThan(notebookAppSource.indexOf('{deleteLabel}'))
    expect(notebookAppSource.indexOf('{deleteLabel}')).toBeLessThan(notebookAppSource.indexOf('{revealLabel}'))
  })

  it('exposes native notebook item reveal for sidebar file locations', () => {
    expect(electronApiSource).toContain('revealNotebookItemLocation?:')
    expect(preloadSource).toContain("revealNotebookItemLocation: (payload) => ipcRenderer.invoke('reveal-notebook-item-location', payload)")
    expect(ipcStorageSource).toContain("ipcMain.handle?.('reveal-notebook-item-location'")
  })

  it('registers sidebar file tree icons in the shared app icon set', () => {
    expect(iconSource).toContain("'folder'")
    expect(iconSource).toContain("'folderOpen'")
    expect(iconSource).toContain("'filePlus'")
    expect(iconSource).toContain("'folderPlus'")
    expect(iconSource).not.toContain("'chevronRight'")
    expect(iconSource).not.toContain("'chevronDown'")
    expect(iconSource).not.toContain("'fileText'")
    expect(iconSource).toContain('M20 20a2 2 0 0 0 2-2V8')
    expect(iconSource).toContain('m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20')
    expect(iconSource).toContain('M6 22a2 2 0 0 1-2-2V4')
    expect(iconSource).toContain('M12 10v6')
  })
})
