import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = readFileSync(new URL('./NotebookApp.tsx', import.meta.url), 'utf8')
const appCss = readFileSync(new URL('../App.css', import.meta.url), 'utf8')

describe('NotebookApp editable asset tools', () => {
  it('closes editable asset tool overlays only when the active note changes', () => {
    expect(source).toContain("const previousAssetToolsNoteLocationKeyRef = useRef('')")
    expect(source).toMatch(
      /useEffect\(\(\) => {\s*if \(previousAssetToolsNoteLocationKeyRef\.current === activeNoteLocationKey\) return\s*previousAssetToolsNoteLocationKeyRef\.current = activeNoteLocationKey\s*imageToolsController\.close\(\)\s*mediaToolsController\.close\(\)\s*}, \[activeNoteLocationKey, imageToolsController, mediaToolsController\]\)/,
    )
  })
})

describe('NotebookApp frontmatter modal routing', () => {
  it('blocks structured frontmatter editing when stored YAML is invalid', () => {
    expect(source).toContain("body?.frontmatterStatus === 'invalid'")
    expect(source).toContain('Frontmatter YAML is invalid. Fix the markdown block before using the structured frontmatter editor.')
  })

  it('includes fixed list controls for template settings and note rows', () => {
    expect(source).toContain('aria-label="frontmatter fixed list values"')
    expect(source).toContain('aria-label="frontmatter fixed list default values"')
    expect(source).toContain('frontmatter-fixed-list-choice')
    expect(source).not.toContain('<option value="">no options</option>')
  })
})

describe('NotebookApp sidebar search wiring', () => {
  it('routes metadata filter actions into the sidebar search panel', () => {
    expect(source).toContain('SidebarSearchPanel')
    expect(source).toContain('const [sidebarSearchMode, setSidebarSearchMode] = useState(false)')
    expect(source).toContain('const sidebarSearchVisible = sidebarSearchMode || sidebarSearchActive')
    expect(source).toContain('className={`notebook-icon-button notebook-sidebar-search-mode-toggle ${')
    expect(source).toContain('aria-label="Search notes"')
    expect(source).toContain('const toggleSidebarSearchModeFromButton = useCallback')
    expect(source).toContain('if (sidebarSearchVisible) {')
    expect(source).toContain('onClick={toggleSidebarSearchModeFromButton}')
    expect(source.match(/closeSidebarSearchMode\(\)/g)?.length).toBeGreaterThanOrEqual(3)
    expect(source).toContain('onCloseMode={closeSidebarSearchMode}')
    expect(source).toContain('onClearButtonClick={closeSidebarSearchMode}')
    expect(source).toContain('if (query.trim().length <= 0 && !hasSidebarSearchFilterKeys(nextFilter)) shouldCloseSearchMode = true')
    expect(source).toContain("activateSidebarSearchKey('synced', key)")
    expect(source).toContain("activateSidebarSearchKey('tags', key)")
    expect(source).toContain("activateSidebarSearchKey('frontmatter', getFrontmatterTemplateFilterKey(templateId))")
    expect(source).toContain('onOpenTagFilter={filterTag}')
    expect(source).toContain('onFilterTemplate={filterFrontmatterTemplateFromModal}')
    expect(source).not.toContain('notebook-sidebar-search-toggle')
    expect(source).not.toContain('frontmatterTemplateFilterAisleIds={frontmatterTemplateFilterAisleIds}')
    expect(source).not.toContain('onFilterAisleFrontmatterTemplate={filterAisleFrontmatterTemplate}')
  })
})

describe('NotebookApp sidebar resize handle', () => {
  it('uses an explicit capsule handle with double-click reset', () => {
    expect(source).toContain('const resetSidebarWidth = useCallback')
    expect(source).toContain('sidebarWidth: clampSidebarWidth(DEFAULT_UI_SETTINGS.sidebarWidth)')
    expect(source).toContain('className="notebook-sidebar-resize-handle"')
    expect(source).toContain('data-app-tooltip="Drag to resize. Double click to reset."')
    expect(source).toContain('onDoubleClick={resetSidebarWidth}')
    expect(source).toContain('className="notebook-sidebar-resize-capsule"')
    expect(appCss).toContain('--notebook-topbar-content-height: calc(')
    expect(appCss).toContain('--notebook-topbar-height: calc(var(--notebook-topbar-content-height) + 1px);')
    expect(appCss).toContain('--resize-handle-width: calc(1.4rem + 2px);')
    expect(appCss).toContain('--resize-handle-height: calc(4.4rem + 4px);')
    expect(appCss).toContain('--resize-handle-half-height: calc(2.2rem + 2px);')
    expect(appCss).toContain('--resize-handle-capsule-width: calc(0.34rem + 2px);')
    expect(appCss).toContain('--resize-handle-capsule-height: calc(3rem + 4px);')
    expect(appCss).toContain('--resize-handle-center-y: calc(var(--notebook-topbar-height) + (100vh - var(--notebook-topbar-height)) * 0.7);')
    expect(appCss).not.toContain('--sidebar-resize-handle-top')
    expect(appCss).toContain('.notebook-sidebar {\n  flex: 0 0 auto;\n  position: relative;\n  z-index: 40;')
    expect(appCss).toContain('.notebook-sidebar-header {\n  box-sizing: border-box;\n  display: flex;\n  align-items: center;\n  gap: var(--notebook-sidebar-control-gap);\n  min-height: var(--notebook-topbar-height);')
    expect(appCss).toContain('.notebook-shell .note-shared-toolbar.toastui-editor-toolbar {\n  --editor-toolbar-spacer-width: 0.55rem;\n  border-bottom: 1px solid var(--notebook-topbar-border) !important;\n  min-height: var(--notebook-topbar-height) !important;')
    expect(appCss).toContain('min-height: var(--notebook-topbar-content-height) !important;\n  padding: var(--notebook-topbar-block-padding) var(--notebook-topbar-inline-padding) !important;')
    expect(appCss).toContain('.notebook-utility-header {\n  flex: 0 0 auto;\n  box-sizing: border-box;\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  gap: var(--notebook-sidebar-control-gap);\n  min-height: var(--notebook-topbar-height);')
    expect(appCss).toContain('.notebook-sidebar-resize-handle {\n  position: absolute;\n  z-index: 6;\n  top: var(--resize-handle-center-y);')
    expect(appCss).toContain('border: 1px solid var(--note-aisle-resize-border);')
    expect(appCss).toContain('background: var(--note-aisle-resize-bg);')
    expect(appCss).toContain('background: var(--note-aisle-resize-hover-bg);')
    expect(appCss).toContain('outline: 2px solid var(--note-aisle-resize-focus-outline);')
    expect(appCss).toContain('.notebook-sidebar-resize-capsule')
    expect(appCss).not.toContain('.notebook-sidebar-resize-handle::before')
  })
})

describe('NotebookApp zoom HUD', () => {
  it('shows native app zoom changes without using the toast stack', () => {
    expect(source).toContain('const [zoomHudPercent, setZoomHudPercent] = useState<number | null>(null)')
    expect(source).toContain('const zoomHudTimeoutRef = useRef<number | null>(null)')
    expect(source).toContain('window.electronAPI?.onAppZoomChanged?.((payload) => {')
    expect(source).toContain('setZoomHudPercent(Math.round(payload.percent))')
    expect(source).toContain('setZoomHudPercent(null)')
    expect(source).toContain('className="app-zoom-hud"')
    expect(appCss).toContain('.app-zoom-hud')
    expect(appCss).toContain('top: calc(var(--notebook-topbar-height) + 0.65rem);')
    expect(appCss).toContain('@keyframes zoomHudFadeIn')
  })
})

describe('NotebookApp tag autocomplete wiring', () => {
  it('connects editor tag autocomplete to the existing tag index and menu', () => {
    expect(source).toContain("import { TagAutocompleteMenu } from '../components/editor/TagAutocompleteMenu'")
    expect(source).toContain("import { useTagAutocompleteController } from '../tags/useTagAutocompleteController'")
    expect(source).toContain("const TAG_AUTOCOMPLETE_RECENT_STORAGE_KEY = 'aislenote:tag-autocomplete-recent:v1'")
    expect(source).toContain('const [tagAutocompleteRecentKeys, setTagAutocompleteRecentKeys] = useState(loadTagAutocompleteRecentKeys)')
    expect(source).toContain('const tagAutocompleteRefreshRef = useRef<(() => void) | null>(null)')
    expect(source).toContain('onTagAutocompleteQueryChange: refreshTagAutocompleteFromEditor')
    expect(source).toContain('const tagAutocompleteController = useTagAutocompleteController({')
    expect(source).toContain('getAvailableTags: () => tagAutocompleteFilterIndex.availableOptions')
    expect(source).toContain('commitActiveEditorMarkdownNow: notebookEditors.commitActiveEditorMarkdownNow')
    expect(source).toContain('tagAutocompleteRefreshRef.current = tagAutocompleteController.refreshQuery')
    expect(source).toContain('<TagAutocompleteMenu')
    expect(source).toContain('onChoose={tagAutocompleteController.acceptSuggestion}')
  })
})

describe('NotebookApp heading collapse wiring', () => {
  it('persists heading collapse state through the notebook editor hook', () => {
    expect(source).toContain("import { isHeadingCollapsed, setHeadingCollapsed } from '../editor/heading-collapse-state'")
    expect(source).toContain('const toggleHeadingCollapse = useCallback')
    expect(source).toContain('const nextCollapsed = !isHeadingCollapsed(previous.ui.headingCollapseState, noteBodyId, aisleId, headingKey)')
    expect(source).toContain('const nextHeadingCollapseState = setHeadingCollapsed(')
    expect(source).toContain('headingCollapseState: nextHeadingCollapseState')
    expect(source).toContain('const expandHeadingCollapse = useCallback')
    expect(source).toContain('headingKey,\n          false,')
    expect(source).toContain('headingCollapseState: state.ui.headingCollapseState')
    expect(source).toContain('onToggleHeadingCollapse: toggleHeadingCollapse')
    expect(source).toContain('onExpandHeadingCollapse: expandHeadingCollapse')
  })
})

describe('NotebookApp large notebook performance wiring', () => {
  it('builds sidebar search indexes from narrow notebook index dependencies instead of whole app state', () => {
    expect(source).toContain("import { createNotebookIndexContext } from '../filters/notebook-index-context'")
    expect(source).toContain('const notebookIndexContext = useMemo(')
    expect(source).toContain('() => createNotebookIndexContext(stateRef.current)')
    expect(source).toContain('state.notebook.items')
    expect(source).toContain('state.noteBodies')
    expect(source).toContain('state.noteAisleBodies')
    expect(source).toContain('const sidebarSearchNeedsFullIndexes = sidebarSearchMode || query.trim().length > 0 || sidebarSearchHasFilterKeys')
    expect(source).toContain("() => buildNoteFilterIndex(notebookIndexContext.state, 'tags', [], notebookIndexContext)")
    expect(source).toContain('return buildSidebarSearchIndexes(notebookIndexContext.state, notebookIndexContext)')
    expect(source).toContain('...getEmptySidebarSearchIndexes(),')
    expect(source).toContain('context: notebookIndexContext,')
    expect(source).not.toContain('const sidebarSearchIndexes = useMemo(() => buildSidebarSearchIndexes(state), [state])')
  })

  it('keeps theme CSS variables and active note resolution off whole-state dependencies', () => {
    expect(source).toContain('...getThemePaletteVariables({')
    expect(source).toContain('state.ui.themePalettes,')
    expect(source).toContain('state.ui.toolbarButtonScale,')
    expect(source).not.toContain('[defaultToolbarButtonScale, state]')
    expect(source).toContain('[state.noteAisleBodies, state.noteBodies, state.notebook.activeNoteId, state.notebook.items, stateRef]')
    expect(source).toContain('[state.noteAisleBodies, state.noteBodies, state.scratchpad, stateRef]')
  })

  it('flushes debounced editor changes before state-backed navigation, search, find, and storage reads', () => {
    expect(source).toContain('notebookEditors.flushPendingEditorAppStateCommit()')
    expect(source).toMatch(/const getLatestNotebookStateFromMountedEditors = useCallback\(\(\) => {\s*notebookEditors\.flushPendingEditorAppStateCommit\(\)/)
    const navigationStart = source.indexOf('const applyNotebookNavigationLocation = useCallback')
    const navigationEnd = source.indexOf('const selectNoteTab = useCallback', navigationStart)
    const navigationBody = source.slice(navigationStart, navigationEnd)
    expect(navigationBody).toContain('notebookEditors.flushPendingEditorAppStateCommit()')
    expect(navigationBody).toContain("recordNotebookNavigationTiming('notebook-navigation'")
    expect(source).toMatch(/const updateSidebarSearchQuery = useCallback\(\s*\(nextQuery: string\) => {\s*notebookEditors\.flushPendingEditorAppStateCommit\(\)/)
    expect(source).toMatch(/const updateFindReplaceQuery = useCallback\(\(nextQuery: string\) => {\s*notebookEditors\.flushPendingEditorAppStateCommit\(\)/)
  })

  it('memoizes and virtualizes the sidebar tree over the large-notebook threshold', () => {
    expect(source).toContain('const NOTEBOOK_TREE_VIRTUALIZATION_THRESHOLD = 300')
    expect(source).toContain('function flattenVisibleNotebookTreeRows(')
    expect(source).toContain('const MemoizedTreeItemRow = React.memo(TreeItemRow)')
    expect(source).toContain('const notebookTreeFlatRows = useMemo(')
    expect(source).toContain('const useVirtualizedNotebookTree = notebookTreeFlatRows.length > NOTEBOOK_TREE_VIRTUALIZATION_THRESHOLD')
    expect(source).toContain('className="notebook-tree-virtual-spacer"')
    expect(source).toContain('className="notebook-tree-virtual-row"')
    expect(source).toContain('renderChildren={false}')
    expect(appCss).toContain('.notebook-tree-virtual-spacer')
    expect(appCss).toContain('.notebook-tree-virtual-row')
  })

  it('uses a local draft palette before debounced global theme commits', () => {
    expect(source).toContain('const [draftPalette, setDraftPalette] = useState(committedPalette)')
    expect(source).toContain('const paletteCommitTimerRef = useRef<number | null>(null)')
    expect(source).toContain('const scheduleThemePaletteCommit = (themeId: AppTheme, palette: typeof committedPalette) => {')
    expect(source).toContain('paletteCommitTimerRef.current = window.setTimeout(() => {')
    expect(source).toContain('setDraftPalette(nextPalette)')
    expect(source).toContain('scheduleThemePaletteCommit(themeId, nextPalette)')
    expect(source).toContain('onPreviewChange={(value) => updatePaletteSlot(slot, value)}')
    expect(source).toContain('onCommit={(value) => commitPaletteSlot(slot, value)}')
  })

  it('keeps closed note tab history transient and wires reopen through navigation', () => {
    expect(source).toContain('const CLOSED_NOTE_TAB_HISTORY_LIMIT = 20')
    expect(source).toContain('const closedNoteTabHistoryRef = useRef<ClosedNotebookTab[]>([])')
    expect(source).toContain('const closedTab = getClosedNotebookTab(snapshotState.notebook, noteId)')
    expect(source).toContain('rememberClosedNoteTab(closedTab)')
    expect(source).toContain('{ restoreClosedTab: closedTab }')
    expect(source).toContain('restoreClosedNotebookTab(previousWithCursor.notebook, options.restoreClosedTab)')
    expect(source).toContain('reopenClosedNoteTab,')
  })
})

describe('NotebookApp find replace wiring', () => {
  it('keeps keyboard find available while the toolbar magnifier opens notes search', () => {
    expect(source).toContain("import { FindReplacePanel } from '../components/editor/FindReplacePanel'")
    expect(source).toContain("import { getFindReplaceShortcutMode } from '../components/editor/find-replace-shortcuts'")
    expect(source).toContain('const [findReplaceOpen, setFindReplaceOpen] = useState(false)')
    expect(source).toContain('const findReplaceMatches = useMemo')
    expect(source).toContain('findVisibleMatches(')
    expect(source).toContain("      'note',\n      findReplaceQuery,")
    expect(source).toContain('if (editor) notebookEditors.commitActiveEditorMarkdownNow(editor)')
    expect(source).toContain('const openFindReplace = useCallback')
    expect(source).toContain('if (!mode) return')
    expect(source).toContain('onOpenFindReplace={focusNotesFilterFromShortcut}')
    expect(source).toContain('setFindReplaceOpen(false)')
    expect(source).toContain('<FindReplacePanel')
    expect(source).not.toContain('replaceMode={findReplaceMode')
    expect(source).not.toContain('scope={findReplaceScope}')
    expect(source).not.toContain('notebook-sidebar-search-toggle')
    expect(source).not.toContain('onOpenFindReplace={() => undefined}')
  })
})

describe('NotebookApp notebook manager wiring', () => {
  it('renames the Data storage tab to Notebooks while keeping the storage section id', () => {
    expect(source).toContain("{ id: 'storage', label: 'Notebooks' }")
    expect(source).toContain("setDataSettingsSection('storage')")
    expect(source).not.toContain("{ id: 'storage', label: 'Storage' }")
  })

  it('renders the inline notebook manager instead of the old storage summary card', () => {
    expect(source).toContain('const renderNotebookManager = () => {')
    expect(source).toContain('useStorageProfileController({')
    expect(source).toContain('beforeStorageAction: commitNotebookBeforeStorageAction')
    expect(source).toContain('commitAppStateNow(latest.state, {')
    expect(source).toContain('New Notebook')
    expect(source).toContain('function NotebookNameDialog({')
    expect(source).toContain("const actionLabel = dialog.mode === 'create' ? 'Select folder' : 'Rename'")
    expect(source).toMatch(/<button type="submit" className="notebook-settings-action" disabled=\{!canSubmit\}>\s*\{actionLabel\}\s*<\/button>\s*<button type="button" className="notebook-settings-action" onClick=\{onCancel\}>\s*Cancel\s*<\/button>/)
    expect(source).toContain("setNotebookNameDialog({ mode: 'create', initialName: 'New Notebook' })")
    expect(source).toContain("setNotebookNameDialog({ mode: 'rename', initialName: notebook.notebookName, notebook })")
    expect(source).toContain('<NotebookNameDialog')
    expect(source).toContain('storageProfileController.chooseNotebookLocation()')
    expect(source).toContain('storageProfileController.createNotebook({ name, locationPath })')
    expect(source).toContain('const renameNotebookFromSettings = useCallback((notebook: KnownNotebook) => {')
    expect(source).toContain('storageProfileController.renameNotebook(name, getNotebookSelector(dialog.notebook))')
    expect(source).toContain('notebookId: storageProfileStatus.activeNotebookId ?? undefined,')
    expect(source).toContain('onClick={() => renameNotebookFromSettings(notebook)}')
    expect(source).toContain('Remembered notebooks')
    expect(source).toContain('iconId="ellipsisVertical"')
    expect(source).toContain('runCurrentNotebookAction(() => void storageProfileController.moveStorageProfile())')
    expect(source).toContain('runCurrentNotebookAction(() => void storageProfileController.revealStorageProfile())')
    expect(source).toContain('Remove from List')
    expect(source).toContain('Delete Notebook')
    expect(source).toContain('desktopNotebookSetupRequired')
    expect(source).toContain('const renderNotebookSetupScreen = () => (')
    expect(source).toContain("const NOTEBOOK_SETUP_APP_NAME = 'AisleNote'")
    expect(source).toContain("const NOTEBOOK_SETUP_LOGO_SRC = './favicon.svg'")
    expect(source).toContain('runtimeVersionLabel')
    expect(source).toContain('Create new notebook')
    expect(source).toContain('Name a notebook, then choose the parent folder.')
    expect(source).toContain('Open notebook folder')
    expect(source).toContain('Choose an existing AisleNote notebook folder.')
    expect(appCss).toContain('.notebook-frontmatter-modal.notebook-name-modal')
    expect(source).not.toContain('window.prompt(')
    expect(source).not.toContain('Open Notebook Folder')
    expect(source).not.toContain('renameCurrentNotebookFromSettings')
    expect(source).not.toContain('notebook-manager-meta-grid')
    expect(appCss).not.toContain('notebook-manager-meta-grid')
    expect(source).not.toContain('<span>status</span>')
    expect(source).not.toContain('<span>health</span>')
    expect(source).not.toContain('<span>writable</span>')
    expect(source).not.toContain('<span>schema</span>')
    expect(source).not.toContain('void storageProfileController.createNotebook()')
    expect(source).not.toContain('storageProfileController.renameNotebook(name, notebook ? getNotebookSelector(notebook) : undefined)')
    expect(source).not.toContain('Create a new notebook under a folder.')
    expect(source).not.toContain('Create or open a notebook')
    expect(source).not.toContain('Put that folder in iCloud, Dropbox, OneDrive')
    expect(source).not.toContain('listSearchableNoteLocations(state).length.toLocaleString()')
    expect(source).not.toContain('serializedState: getSerializedStateForStorageAction')
  })

  it('uses setup-specific theme-aware startup styling', () => {
    expect(appCss).toContain('.notebook-setup-brand')
    expect(appCss).toContain('.notebook-setup-action-row')
    expect(appCss).toContain('.notebook-setup-action-button.is-primary')
    expect(appCss).toContain('background: var(--app-page-bg)')
    expect(appCss).toContain('background: var(--app-surface-raised)')
    expect(appCss).toContain('border: 1px solid var(--app-border-muted)')
  })

  it('subscribes to the Electron Open Notebook menu navigation event', () => {
    expect(source).toContain('onOpenNotebookManager?.(openNotebookManagerSettings)')
    expect(source).toContain("openUtilityView('settings')")
    expect(source).toContain("setSettingsSection('data')")
    expect(source).toContain("setDataSettingsSection('storage')")
  })
})

describe('NotebookApp aisle insertion focus', () => {
  it('routes shortcut and context-menu aisle creation through pending editor focus', () => {
    expect(source).toContain('addAisleFromNewlineRef.current = addAisle')
    expect(source).toContain('const insertEditorContextAisle = useCallback(')
    expect(source).toContain('addAisle(side, aisleId)')
    expect(source).toContain('pendingFocusToAisleIdRef.current = createdAisleId')
    expect(source).toContain('pendingScrollToAisleIdRef.current = createdAisleId')
    expect(source).toContain('pendingCursorRestoreRef.current = {')
    expect(source).toContain('aisleId: createdAisleId')
    expect(source).toContain("focusIntent: 'aisle-activation'")
    expect(source).toContain('setActiveAisleId(createdAisleId)')
    expect(source).not.toContain('window.setTimeout(() => setActiveAisleId(aisle.id), 0)')
  })
})
