import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const vaultAppSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), './VaultApp.tsx'), 'utf8')
const appCssSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), '../App.css'), 'utf8')
const baseCssSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), '../styles/base.css'), 'utf8')
const editorShellCssSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), '../styles/editor-shell.css'), 'utf8')
const settingsCssSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), '../styles/settings.css'), 'utf8')
const themeSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), '../theme/vault-themes.ts'), 'utf8')
const lightCssSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), '../styles/themes/light.css'), 'utf8')
const cheeseCssSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), '../styles/themes/cheese.css'), 'utf8')

describe('vault settings access', () => {
  it('renders explicit settings entry points for expanded and collapsed sidebars', () => {
    expect(vaultAppSource).toContain('const handleSidebarSettingsClick = useCallback(() => {')
    expect(vaultAppSource).toContain("if (viewMode === 'settings') {")
    expect(vaultAppSource).toContain("setViewMode('main')")
    expect(vaultAppSource).toContain("openUtilityView('settings')")
    expect(vaultAppSource).toContain('onClick={handleSidebarSettingsClick}')
    expect(vaultAppSource).toContain('Settings')
    expect(vaultAppSource).toContain('aria-label="Open settings"')
    expect(vaultAppSource).toContain('title="Open settings"')
    expect(vaultAppSource).toContain('iconId="settings"')
    expect(appCssSource).toContain('.vault-sidebar .vault-icon-button:active')
    expect(appCssSource).toContain('.vault-sidebar .vault-icon-button:focus-visible')
    expect(appCssSource).toContain('border-color: transparent;')
    expect(appCssSource).toContain('background: transparent;')
    expect(appCssSource).toContain('outline: 2px solid var(--vault-action-accent);')
    expect(appCssSource).toContain('background: var(--vault-sidebar-active-bg);')
    expect(vaultAppSource).not.toContain('Utility\\n')
  })

  it('aligns tabbed utility content with its content panels', () => {
    expect(vaultAppSource).toContain('className="vault-utility-content vault-settings-panel"')
    expect(vaultAppSource).toContain('className="vault-utility-content vault-tabbed-utility-panel" aria-label="Messages"')
    expect(vaultAppSource).toContain('className="vault-utility-content vault-tabbed-utility-panel" aria-label="About"')
    expect(vaultAppSource).toContain('className="vault-utility-content vault-trash-panel" aria-label="Trash"')
    expect(appCssSource).toContain('.vault-settings-panel > .vault-utility-tabs,\n.vault-tabbed-utility-panel > .vault-utility-tabs')
    expect(appCssSource).toContain('margin: 0 auto 8px;')
    expect(appCssSource).not.toContain('padding-inline: 14px;')
    expect(appCssSource).toContain('.vault-utility-content .utility-page-card {\n  width: min(960px, 100%);\n  margin-inline: auto;')
    expect(appCssSource).toContain('.vault-utility-content .utility-page-card.messages-view-card-diagnostics {\n  width: min(76rem, 100%);')
    expect(appCssSource).toContain('.vault-trash-panel > .vault-utility-panel-header')
    expect(appCssSource).toContain('.vault-trash-panel > .vault-settings-help')
    expect(appCssSource).toContain('.vault-trash-table {\n  display: grid;\n  width: min(960px, 100%);\n  margin-inline: auto;')
  })

  it('labels data import settings without obsolete replacement language', () => {
    expect(vaultAppSource).toContain("{ id: 'transfer', label: 'Import' }")
    expect(vaultAppSource).toContain('Imports add a new top-level folder to the current vault.')
    expect(vaultAppSource).toContain('without replacing existing notes')
    expect(vaultAppSource).not.toContain("{ id: 'transfer', label: 'Transfer' }")
    expect(vaultAppSource).not.toContain('AisleNote vault imports replace the current vault.')
    expect(vaultAppSource).not.toContain('Import vault or Markdown')
  })

  it('uses vault-native hotkeys and exposes the scratchpad shortcut row', () => {
    expect(vaultAppSource).toContain('useVaultHotkeys({')
    expect(vaultAppSource).not.toContain('useGlobalHotkeys')
    expect(vaultAppSource).toContain("{ id: 'openSettings', label: 'Open settings' }")
    expect(vaultAppSource).toContain("{ id: 'toggleNotesScratchpad', label: 'Toggle scratchpad' }")
    expect(vaultAppSource).toContain("{ id: 'newNote', label: 'New note' }")
    expect(vaultAppSource).toContain("{ id: 'newFolder', label: 'New folder' }")
    expect(vaultAppSource).toContain("{ id: 'formatHighlight', label: 'Highlight' }")
  })

  it('uses platform-aware vault hotkey recorder buttons', () => {
    expect(vaultAppSource).toContain('buildShortcutFromKeyboardEvent')
    expect(vaultAppSource).toContain('settings-shortcut-btn')
    expect(vaultAppSource).toContain('formatShortcutLabel(shortcut, isMacPlatform)')
    expect(vaultAppSource).not.toContain('placeholder={formatShortcutLabel(DEFAULT_SHORTCUTS[row.id] ?? \'\', isMacPlatform)}')
  })

  it('restores shortcut menu configuration in vault settings', () => {
    expect(vaultAppSource).toContain('ShortcutMenuSettingsPanel')
    expect(vaultAppSource).toContain('NEWLINE_OPERATION_LABELS.operationsMenu')
    expect(vaultAppSource).toContain('updateShortcutMenuOperationsSetting')
    expect(vaultAppSource).toContain('onOpenTableOfContents: openTableOfContentsFromEditorShortcut')
    expect(vaultAppSource).toContain("operation === 'tableOfContents'")
  })

  it('removes obsolete permanent delete setting from active vault settings', () => {
    expect(vaultAppSource).not.toContain('Confirm permanent delete')
    expect(vaultAppSource).not.toContain('trashDeleteForRealRequiresConfirmation')
    expect(vaultAppSource).toContain("window.confirm('Permanently delete this item? This cannot be undone.')")
  })

  it('uses restored vault misc and frontmatter settings controls', () => {
    expect(vaultAppSource).toContain('settings-segmented-control settings-flag-segmented-control')
    expect(vaultAppSource).toContain('VaultSettingsSwitch')
    expect(vaultAppSource).toContain('frontmatterDraft')
    expect(vaultAppSource).toContain('Template changes apply only after saving.')
    expect(vaultAppSource).not.toContain('Scratchpad aisle limit')
    expect(vaultAppSource).not.toContain('MIN_SCRATCHPAD_AISLE_LIMIT')
    expect(vaultAppSource).not.toContain('MAX_SCRATCHPAD_AISLE_LIMIT')
    expect(vaultAppSource).not.toContain('DEFAULT_SCRATCHPAD_AISLE_LIMIT')
    expect(vaultAppSource).not.toContain('clampScratchpadAisleLimit')
    expect(vaultAppSource).toContain("{ id: 'focused-aisle', label: 'Current aisle' }")
    expect(vaultAppSource).not.toContain('Math.max(1, Math.min(12')
  })

  it('supports dragging frontmatter template fields without reordering the template list', () => {
    expect(vaultAppSource).toContain('FRONTMATTER_TEMPLATE_FIELD_DRAG_MIME')
    expect(vaultAppSource).toContain('reorderFrontmatterTemplateFieldsByTargetIndex')
    expect(vaultAppSource).toContain('data-frontmatter-template-field-id')
    expect(vaultAppSource).toContain('frontmatter-template-field-drag-handle')
    expect(vaultAppSource).toContain('frontmatter-template-select')
    expect(vaultAppSource).toContain('className="frontmatter-template-toolbar"')
    expect(vaultAppSource).toContain('className="frontmatter-template-actions"')
    expect(vaultAppSource).toContain('className="frontmatter-template-add-field-row"')
    expect(vaultAppSource).toContain('className="frontmatter-template-add-field-btn"')
    expect(vaultAppSource).toContain('iconId="plus"')
    expect(vaultAppSource).toContain('className="frontmatter-template-footer-actions"')
    expect(vaultAppSource).toContain('setFrontmatterTemplateDeleteTargetId(activeTemplate.id)')
    expect(vaultAppSource).toContain('Are you sure you want to delete this template? This cannot be undone.')
    expect(vaultAppSource).not.toContain('FRONTMATTER_TEMPLATE_DRAG_MIME')
    expect(vaultAppSource).not.toContain('reorderFrontmatterTemplatesByInsertion')
    expect(vaultAppSource).not.toContain('dropFrontmatterTemplate(event, template.id)')
    expect(vaultAppSource).not.toContain('className="frontmatter-template-list"')
    expect(vaultAppSource).not.toContain('frontmatter-template-drag-handle')
    expect(settingsCssSource).toContain('.frontmatter-template-settings-layout')
    expect(settingsCssSource).not.toContain('.vault-settings-section.frontmatter-template-settings-section')
    expect(settingsCssSource).toContain('.frontmatter-template-toolbar')
    expect(settingsCssSource).toContain('.frontmatter-template-actions')
    expect(settingsCssSource).toContain('.frontmatter-template-add-field-row')
    expect(settingsCssSource).toContain('.frontmatter-template-add-field-btn')
    expect(settingsCssSource).toContain('.frontmatter-template-footer-actions')
    expect(settingsCssSource).toContain('flex-wrap: wrap;')
    expect(settingsCssSource).toContain('.frontmatter-template-delete-modal')
    expect(settingsCssSource).toContain('.frontmatter-template-field-row.is-drop-index-before::before')
    expect(settingsCssSource).toContain('.frontmatter-template-field-drag-handle')
    expect(settingsCssSource).not.toContain('.frontmatter-template-list-item.is-drop-before::before')
  })

  it('keeps vault settings labels normal weight and switches pill-shaped', () => {
    expect(appCssSource).toContain('.vault-utility-content label:not([class])')
    expect(appCssSource).toContain('font-weight: 400;')
    expect(settingsCssSource).toContain('width: 2.35rem;')
    expect(settingsCssSource).toContain('height: 1.22rem;')
    expect(settingsCssSource).toContain('border-radius: 999px;')
  })

  it('shows percent readouts for visual scale sliders with standard text and matching active tracks', () => {
    expect(vaultAppSource).toContain('formatScalePercent(noteFontScale)')
    expect(vaultAppSource).toContain('formatScalePercent(toolbarButtonScale)')
    expect(vaultAppSource).toContain('getRangeProgressStyle(noteFontScale, MIN_NOTE_FONT_SCALE, MAX_NOTE_FONT_SCALE)')
    expect(vaultAppSource).toContain('getRangeProgressStyle(toolbarButtonScale, MIN_TOOLBAR_BUTTON_SCALE, MAX_TOOLBAR_BUTTON_SCALE)')
    expect(vaultAppSource).toContain('id="note-font-scale-value"')
    expect(vaultAppSource).toContain('id="toolbar-button-scale-value"')
    expect(vaultAppSource).toContain('MIN_NOTE_FONT_SCALE')
    expect(vaultAppSource).toContain('MAX_NOTE_FONT_SCALE')
    expect(vaultAppSource).toContain('MIN_TOOLBAR_BUTTON_SCALE')
    expect(vaultAppSource).toContain('MAX_TOOLBAR_BUTTON_SCALE')
    expect(settingsCssSource).toContain('min-width: 3.4rem;')
    expect(settingsCssSource).toContain('font-variant-numeric: tabular-nums;')
    expect(settingsCssSource).toContain('--settings-range-progress: 0%;')
    expect(settingsCssSource).toContain('var(--settings-range-thumb-bg) var(--settings-range-progress)')
    expect(settingsCssSource).toContain('var(--settings-range-thumb-hover-bg) var(--settings-range-progress)')
    expect(settingsCssSource).toContain('var(--settings-range-track-hover-bg) var(--settings-range-progress)')
    expect(baseCssSource).toContain('--settings-range-value-text: var(--app-text-heading);')
    expect(baseCssSource).toContain('--settings-range-thumb-hover-bg: var(--app-primary-hover);')
    expect(lightCssSource).toContain('--settings-range-thumb-hover-bg: #355f92;')
    expect(lightCssSource).toContain('--settings-range-value-text: var(--app-text-heading);')
    expect(cheeseCssSource).toContain('--settings-range-thumb-hover-bg: color-mix(in srgb, var(--custom-palette-primary) 84%, var(--custom-palette-text));')
    expect(cheeseCssSource).toContain('--settings-range-value-text: var(--app-text-heading);')
    expect(baseCssSource).not.toContain('--settings-range-value-text: var(--custom-palette-primary);')
    expect(baseCssSource).not.toContain('--settings-range-value-text: var(--app-primary);')
  })

  it('adds a no-op guarded copy-to control for selected custom palettes', () => {
    expect(vaultAppSource).toContain('copyActiveThemeToSelectedCustomPalette')
    expect(vaultAppSource).toContain('canCopyActiveThemeToSelectedCustomPalette = state.theme !== selectedCustomTheme')
    expect(vaultAppSource).toContain('copyThemePaletteToCustomPalette(previous.ui.themePalettes, previous.theme, targetTheme)')
    expect(vaultAppSource).toContain('if (previous.theme === targetTheme) return previous')
    expect(vaultAppSource).toContain('className="vault-settings-action settings-theme-copy-button"')
    expect(vaultAppSource).toContain('disabled={!canCopyActiveThemeToSelectedCustomPalette}')
    expect(vaultAppSource).toContain('Copy to')
    expect(vaultAppSource).not.toContain('theme: isCustomTheme(previous.theme) ? themeId : previous.theme,')
    expect(settingsCssSource).toContain('.settings-theme-copy-row')
    expect(settingsCssSource).toContain('.settings-theme-copy-button.vault-settings-action')
  })

  it('restores plain JSON theme import and export controls', () => {
    expect(vaultAppSource).toContain('serializeThemeSettings(draftPalette)')
    expect(vaultAppSource).toContain('parseThemeSettingsImport(themeJsonDraft, draftPalette)')
    expect(vaultAppSource).toContain('className="custom-theme-transfer-actions"')
    expect(vaultAppSource).toContain('className="custom-theme-transfer-actions-left"')
    expect(vaultAppSource).toContain('className="custom-theme-transfer-actions-right"')
    expect(vaultAppSource).toContain('Import theme')
    expect(vaultAppSource).toContain('Export theme')
    expect(vaultAppSource).toContain('Reset selected palette')
    expect(vaultAppSource).toContain('className="settings-text-input custom-theme-json-textarea"')
    expect(vaultAppSource).toContain('readOnly={themeJsonMode === \'export\'}')
    expect(settingsCssSource).toContain('.custom-theme-json-modal')
    expect(settingsCssSource).toContain('.custom-theme-transfer-actions')
    expect(settingsCssSource).toContain('justify-content: space-between;')
    expect(settingsCssSource).toContain('.custom-theme-transfer-actions-right')
  })

  it('renders grouped custom theme palette sections', () => {
    expect(themeSource).toContain("{ label: 'Buttons', slots: ['primary', 'button'] }")
    expect(themeSource).toContain("button: 'Unfocused'")
    expect(vaultAppSource).toContain('CUSTOM_THEME_PALETTE_GROUPS.map((group) => (')
    expect(vaultAppSource).toContain('className="custom-theme-group"')
    expect(vaultAppSource).toContain('aria-label={`${group.label} colors`}')
    expect(vaultAppSource).toContain('className="custom-theme-group-title"')
    expect(vaultAppSource).not.toContain('CUSTOM_THEME_PALETTE_SLOTS.map((slot) => (')
    expect(settingsCssSource).toContain('.custom-theme-grid')
    expect(settingsCssSource).toContain('grid-template-columns: minmax(0, 1fr);')
    expect(settingsCssSource).toContain('.custom-theme-group')
    expect(settingsCssSource).toContain('grid-template-columns: repeat(2, minmax(0, 1fr));')
    expect(settingsCssSource).toContain('.custom-theme-group-title')
    expect(settingsCssSource).toContain('grid-column: 1 / -1;')
    expect(settingsCssSource).toContain('.custom-theme-group > .custom-theme-slot:nth-child(odd)')
    expect(settingsCssSource).toContain('grid-template-columns: minmax(5.35rem, 1fr) var(--custom-theme-color-size) minmax(5.1rem, max-content);')
  })

  it('uses theme-specific aisle resize affordance colors', () => {
    expect(editorShellCssSource).toContain('background: var(--note-aisle-resize-bg);')
    expect(editorShellCssSource).toContain('background: var(--note-aisle-resize-hover-bg);')
    expect(editorShellCssSource).toContain('outline: 2px solid var(--note-aisle-resize-focus-outline);')
    expect(baseCssSource).toContain('--note-aisle-resize-hover-bg: var(--app-primary-border);')
    expect(lightCssSource).toContain('--note-aisle-resize-hover-bg: #607da4;')
    expect(cheeseCssSource).toContain('--note-aisle-resize-bg: var(--app-border);')
    expect(cheeseCssSource).toContain('--note-aisle-resize-border: transparent;')
    expect(cheeseCssSource).toContain('--note-aisle-resize-hover-bg: color-mix(in srgb, var(--custom-palette-primary) 72%, var(--custom-theme-sidebar));')
    expect(cheeseCssSource).toContain('--note-aisle-resize-hover-border: transparent;')
  })

  it('derives editor toolbar colors from the sidebar palette for every palette theme', () => {
    expect(baseCssSource).toContain('--custom-palette-button: var(--custom-theme-button, #13264a);')
    expect(baseCssSource).toContain('--editor-toolbar-bg: var(--custom-theme-sidebar, var(--custom-palette-panel));')
    expect(baseCssSource).toContain('--editor-toolbar-hover-bg: color-mix(in srgb, var(--custom-palette-primary) 16%, var(--custom-palette-button));')
    expect(baseCssSource).toContain('--editor-toolbar-active-bg: var(--custom-palette-primary);')
    expect(baseCssSource).toContain('--editor-toolbar-button-bg: var(--custom-palette-button);')
    expect(cheeseCssSource).not.toContain('--editor-toolbar-bg: var(--custom-theme-sidebar);')
  })

  it('previews inactive and active button states in an extra theme aisle', () => {
    expect(vaultAppSource).toContain('className="visuals-preview-aisles"')
    expect(vaultAppSource).toContain('className="vault-utility-tabs visuals-preview-button-tabs"')
    expect(vaultAppSource).toContain('aria-label="Preview button states"')
    expect(vaultAppSource).toContain('Messages')
    expect(vaultAppSource).toContain('className="is-active" tabIndex={-1}')
    expect(vaultAppSource).toContain('Settings')
    expect(settingsCssSource).toContain('--vault-control-bg: var(--app-button);')
    expect(settingsCssSource).toContain('.visuals-preview-control-aisle')
  })
})
