import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const appDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(appDir, '../..')
const vaultAppSource = readFileSync(join(appDir, './VaultApp.tsx'), 'utf8')
const appCssSource = readFileSync(join(appDir, '../App.css'), 'utf8')
const iconSource = readFileSync(join(appDir, '../icons/app-icons.ts'), 'utf8')
const electronApiSource = readFileSync(join(repoRoot, 'src/types/electron-api.d.ts'), 'utf8')
const preloadSource = readFileSync(join(repoRoot, 'electron/preload.cjs'), 'utf8')
const ipcStorageSource = readFileSync(join(repoRoot, 'electron/ipc-storage.mjs'), 'utf8')

describe('vault sidebar tree', () => {
  it('renders a file-tree style sidebar without data transfer actions', () => {
    expect(vaultAppSource).toContain("const folderIconId = isFolder && !collapsed && children.length > 0 ? 'folderOpen' : 'folder'")
    expect(vaultAppSource).toContain('className="vault-tree-folder-icon"')
    expect(vaultAppSource).not.toContain("'chevronRight'")
    expect(vaultAppSource).not.toContain("'chevronDown'")
    expect(vaultAppSource).not.toContain("'fileText'")
    expect(vaultAppSource).toContain('vault-tree-children')
    expect(vaultAppSource).toContain("onSelectFolder={selectSidebarTreeFolder}")
    expect(vaultAppSource).toContain('className="vault-sidebar-header" aria-label="Vault actions"')
    expect(vaultAppSource).toContain('iconId="filePlus"')
    expect(vaultAppSource).toContain('iconId="folderPlus"')
    expect(vaultAppSource).not.toContain('<h1>Vault</h1>')
    expect(vaultAppSource).not.toContain('<button type="button" onClick={createNote}>New note</button>')
    expect(vaultAppSource).not.toContain('<button type="button" onClick={createFolder}>New folder</button>')
    expect(vaultAppSource).not.toContain('vault-sidebar-actions')
    expect(vaultAppSource).not.toContain('vault-utility-nav')
    expect(appCssSource).not.toContain('.vault-sidebar-actions')
    expect(appCssSource).not.toContain('.vault-utility-nav')
    expect(vaultAppSource).not.toContain('<button type="button" onClick={importVault}>Import</button>')
    expect(vaultAppSource).not.toContain('<button type="button" onClick={exportVault}>Export</button>')
  })

  it('uses active styling for the active folder create target and active note row', () => {
    expect(appCssSource).toContain('.vault-tree-row.is-folder.is-active .vault-tree-main')
    expect(appCssSource).not.toContain('.vault-tree-row.is-active .vault-tree-main')
    expect(vaultAppSource).toContain("const [activeFolderId, setActiveFolderId] = useState('')")
    expect(vaultAppSource).toContain('activeFolderId: string')
    expect(vaultAppSource).toContain('activeNoteId: string')
    expect(vaultAppSource).toContain("const activeNote = item.type === 'note' && item.id === activeNoteId")
    expect(vaultAppSource).toContain("const active = (item.type === 'folder' && item.id === activeFolderId) || activeNote")
    expect(vaultAppSource).toContain('activeFolderId={activeFolderId}')
    expect(vaultAppSource).toContain("activeNoteId={activeModelIsScratchpad ? '' : state.vault.activeNoteId}")
    expect(vaultAppSource).toContain("const selected = item.type === 'note' && selectedNoteIds.has(item.id)")
    expect(appCssSource).toContain('--vault-tree-row-bg: color-mix(in srgb, var(--app-text) 10%, transparent);')
    expect(appCssSource).toContain('.vault-tree-children::before')
    expect(appCssSource).toContain('.vault-tree-row {\n  position: relative;\n  min-height: 28px;\n  margin: 0;\n}')
    expect(appCssSource).toContain('min-height: 28px;\n  box-sizing: border-box;')
    expect(appCssSource).toContain('padding: 2px 8px 2px calc(var(--tree-depth, 0) * 12px + 5px);')
    expect(appCssSource).toContain('padding-left: calc(var(--tree-depth, 0) * 12px + 5px);')
    expect(appCssSource).toContain('.vault-tree-children .vault-tree-row.is-note .vault-tree-main')
    expect(appCssSource).toContain('padding-left: calc(var(--tree-depth, 0) * 12px + 11px);')
    expect(appCssSource).toContain('left: calc(var(--tree-depth, 0) * 12px + 13px);')
    expect(appCssSource).toContain('--vault-tree-row-bg: transparent;')
    expect(appCssSource).toContain('background: var(--vault-tree-row-bg);')
    expect(appCssSource).toContain('.vault-tree-folder-icon')
    expect(appCssSource).toContain('height: 20px;')
    expect(appCssSource).toContain('linear-gradient(var(--vault-tree-row-bg), var(--vault-tree-row-bg))')
    expect(appCssSource).toContain('.vault-tree-row.is-note.is-active .vault-tree-main,\n.vault-tree-row.is-note.is-selected .vault-tree-main')
    expect(appCssSource).not.toContain('.vault-tree-row.is-active .vault-tree-main,\n.vault-search-result.is-active')
  })

  it('uses selected note rows for note navigation and clears tree state from root clicks', () => {
    expect(vaultAppSource).toContain('setSelectedTreeNoteIds([resolvedLocation.noteId])')
    expect(vaultAppSource).toContain('setTreeSelectionAnchorNoteId(resolvedLocation.noteId)')
    expect(vaultAppSource).toContain('setSelectedTreeNoteIds(stateRef.current.vault.activeNoteId ? [stateRef.current.vault.activeNoteId] : [])')
    expect(vaultAppSource).toContain('setTreeSelectionAnchorNoteId(stateRef.current.vault.activeNoteId)')
    expect(appCssSource).toContain('.vault-tree-row.is-note.is-selected .vault-tree-main')
  })

  it('uses the active folder as the implicit header create target and clears it from root clicks', () => {
    const createNoteSource = vaultAppSource.slice(
      vaultAppSource.indexOf('const createNoteAt = useCallback'),
      vaultAppSource.indexOf('const createFolderAt = useCallback'),
    )
    const createFolderSource = vaultAppSource.slice(
      vaultAppSource.indexOf('const createFolderAt = useCallback'),
      vaultAppSource.indexOf('const importVault = useCallback'),
    )
    expect(vaultAppSource).toContain("setActiveFolderId(getContainingFolderId(snapshotState.vault.items, resolvedLocation.noteId) ?? '')")
    expect(createNoteSource).toContain('activeFolderId && findVaultFolder(previous.vault.items, activeFolderId)')
    expect(createNoteSource).toContain('? activeFolderId')
    expect(createNoteSource).toContain(': null')
    expect(createNoteSource).not.toContain('getContainingFolderId')
    expect(createNoteSource).toContain("setActiveFolderId(parentFolderIdRef.current ?? '')")
    expect(createFolderSource).toContain('activeFolderId && findVaultFolder(previous.vault.items, activeFolderId)')
    expect(createFolderSource).toContain('? activeFolderId')
    expect(createFolderSource).toContain(': null')
    expect(createFolderSource).not.toContain('getContainingFolderId')
    expect(vaultAppSource).toContain('const clearActiveFolderFromRootTreeClick = useCallback')
    expect(vaultAppSource).toContain('onClick={clearActiveFolderFromRootTreeClick}')
    expect(vaultAppSource).toContain("if (target?.closest('.vault-tree-row, .tab-context-menu')) return")
    expect(vaultAppSource).toContain("setActiveFolderId('')")
    expect(vaultAppSource).toContain('setSelectedTreeNoteIds([])')
    expect(vaultAppSource).toContain("setTreeSelectionAnchorNoteId('')")
  })

  it('supports intentional long-press rename and sidebar drag/drop reordering', () => {
    expect(vaultAppSource).toContain('VAULT_TREE_RENAME_LONG_PRESS_MS = 500')
    expect(vaultAppSource).toContain('onPointerDown={beginLongPressRename}')
    expect(vaultAppSource).toContain('className="vault-tree-rename-input"')
    expect(vaultAppSource).toContain("renamingItemId={renamingItemSurface === 'tree' ? renamingTreeItemId : ''}")
    expect(vaultAppSource).toContain("type VaultTreeRenameCommitSource = 'enter' | 'blur' | 'tab'")
    expect(vaultAppSource).toContain("onBlur={() => onCommitRename('blur')}")
    expect(vaultAppSource).toContain("onCommitRename('enter')")
    expect(vaultAppSource).toContain("event.key === 'Tab' && !event.shiftKey && tabCreatesNext")
    expect(vaultAppSource).toContain("onCommitRename('tab')")
    expect(vaultAppSource).toContain('draggable={!renaming}')
    expect(vaultAppSource).toContain('const shouldExpandDropParent =')
    expect(vaultAppSource).toContain('Boolean(target.parentFolderId) &&')
    expect(vaultAppSource).toContain('(draggedNoteIds.length === 0 || previous.ui.noteDropAutoExpandsFolders === true)')
    expect(vaultAppSource).toContain('moveVaultItems(previous.vault, draggedNoteIds, target.parentFolderId, target.index)')
    expect(vaultAppSource).toContain('moveVaultItem(previous.vault, draggedItemId, target.parentFolderId, target.index)')
    expect(vaultAppSource).toContain('ui: shouldExpandDropParent')
    expect(vaultAppSource).toContain('vault-tree-root-drop-zone')
    expect(appCssSource).toContain('.vault-tree-row.is-drop-before::before')
    expect(appCssSource).toContain('.vault-tree-row.is-drop-inside .vault-tree-main')
    expect(appCssSource).toContain('.vault-tree-root-drop-zone.is-drop-root')
  })

  it('supports note-only multi-selection with shift and command click', () => {
    expect(vaultAppSource).toContain("type VaultTreeNoteSelectionMode = 'replace' | 'toggle' | 'range'")
    expect(vaultAppSource).toContain('aria-multiselectable="true"')
    expect(vaultAppSource).toContain('getVisibleVaultTreeNoteIds(state.vault.items, collapsedFolderIds)')
    expect(vaultAppSource).toContain('getVaultTreeRangeNoteIds(visibleTreeNoteIds, anchorNoteId, noteId)')
    expect(vaultAppSource).toContain("event.shiftKey ? 'range' : event.metaKey || event.ctrlKey ? 'toggle' : 'replace'")
    expect(vaultAppSource).toContain('setSelectedTreeNoteIds([])')
    expect(vaultAppSource).toContain('draggingNoteIds.has(item.id)')
    expect(vaultAppSource).toContain('function getVaultTreeContextDeleteNoteIds(')
    expect(vaultAppSource).toContain("if (!selectedNoteIds.includes(menu.itemId)) return [menu.itemId]")
    expect(vaultAppSource).toContain('visibleNoteIds.filter((noteId) => selectedNoteIdSet.has(noteId))')
    expect(appCssSource).toContain('.vault-tree-row.is-note.is-selected .vault-tree-main')
  })

  it('opens retained note tabs from sidebar middle-click and unmodified double-click', () => {
    expect(vaultAppSource).toContain('onOpenNoteRetained: (noteId: string) => void')
    expect(vaultAppSource).toContain('onOpenNoteRetained(item.id)')
    expect(vaultAppSource).toContain('onDoubleClick={(event) => {')
    expect(vaultAppSource).toContain('event.button !== 0 ||')
    expect(vaultAppSource).toContain('event.metaKey ||')
    expect(vaultAppSource).toContain("applyVaultNavigationLocation({ noteId, aisleId: '' }, { tabDisposition: 'retained' })")
  })

  it('does not keep hidden inline rename or delete controls in note rows', () => {
    expect(vaultAppSource).not.toContain('vault-tree-actions')
    expect(vaultAppSource).not.toContain('vault-tree-action')
    expect(appCssSource).not.toContain('vault-tree-actions')
    expect(appCssSource).not.toContain('vault-tree-action')
    expect(vaultAppSource).not.toContain('onDoubleClick={() => onStartRename(item.id, item.title)}')
    expect(appCssSource).toContain('max-width: 100%;')
    expect(appCssSource).toContain('box-sizing: border-box;')
  })

  it('wires sidebar note activation to vault cursor restore', () => {
    expect(vaultAppSource).toContain('externalStateLoadVersion')
    expect(vaultAppSource).toContain('externalStateLoadVersion, commitAppStateNow } = usePersistentAppState()')
    expect(vaultAppSource).toContain('externalStateLoadVersion,')
    expect(vaultAppSource).toContain('useNoteCursorPersistence')
    expect(vaultAppSource).toContain('usePendingNoteCursorRestore')
    expect(vaultAppSource).toContain('useVaultNavigationHistory')
    expect(vaultAppSource).toContain('resolveVaultNavigationLocation(snapshotState, location)')
    expect(vaultAppSource).toContain('applyVaultNavigationLocation({ noteId, aisleId: \'\' })')
    expect(vaultAppSource).toContain('const snapshots = vaultEditors.getMountedEditorMarkdownSnapshots()')
    expect(vaultAppSource).toContain('const previousWithEditorContent = applyVaultEditorMarkdownSnapshotsToState(previous, snapshots)')
    expect(vaultAppSource).toContain('const previousWithCursor = applyActiveCursorToState(previousWithEditorContent)')
    expect(vaultAppSource).toContain('pendingFocusToAisleIdRef.current = resolvedLocation.aisleId || null')
    expect(vaultAppSource).toContain('if (pendingFocusToAisleIdRef.current !== (resolvedLocation.aisleId || null)) return')
    expect(vaultAppSource).toContain('activateAisleEditor(buildAisleEditorKey(active.noteBody.id, resolvedLocation.aisleId), {')
    expect(vaultAppSource).toContain("source: 'programmatic'")
  })

  it('reveals the active note row in the sidebar tree after vault note changes', () => {
    expect(vaultAppSource).toContain("import { getVaultTreeRevealScrollTop } from './vault-tree-scroll'")
    expect(vaultAppSource).toContain('const activeNoteTreeRevealNoteIdRef = useRef(state.vault.activeNoteId)')
    expect(vaultAppSource).toContain("const pendingActiveNoteTreeRevealIdRef = useRef('')")
    expect(vaultAppSource).toContain('const suppressActiveNoteTreeRevealForDeleteRef = useRef<string | null>(null)')
    expect(vaultAppSource).toContain('pendingActiveNoteTreeRevealIdRef.current = activeNoteId')
    expect(vaultAppSource).toContain('suppressActiveNoteTreeRevealForDeleteRef.current === previousActiveNoteId')
    expect(vaultAppSource).toContain('if (scratchpadActive || activeModelIsScratchpad) {')
    expect(vaultAppSource).toContain('const collapsedAncestorIds = getVaultNoteFolderPath(state.vault.items, pendingNoteId)')
    expect(vaultAppSource).toContain('previous.ui.collapsedFolderIds.filter(')
    expect(vaultAppSource).toContain('data-vault-tree-item-id={item.id}')
    expect(vaultAppSource).toContain("scrollNode.querySelectorAll<HTMLElement>('[data-vault-tree-item-id]')")
    expect(vaultAppSource).toContain("querySelector<HTMLElement>('.vault-sidebar-footer:not(.is-collapsed)')")
    expect(vaultAppSource).toContain('bottomInset: obscuredBottomInset')
    expect(vaultAppSource).toContain('rowIndex * VAULT_TREE_VIRTUAL_ROW_HEIGHT')
    expect(vaultAppSource).toContain('const nextScrollTop = getVaultTreeRevealScrollTop(')
    expect(vaultAppSource).toContain('if (Math.abs(nextScrollTop - scrollNode.scrollTop) > 0.5) {')
    expect(vaultAppSource).toContain('updateVaultTreeViewport()')
  })

  it('suppresses sidebar tree reveal scrolling when deletion changes the active note', () => {
    expect(vaultAppSource).toContain('function deletedVaultItemsContainNoteId(')
    expect(vaultAppSource).toContain('return item.children.some((child) => vaultTreeItemContainsNoteId(child, noteId))')
    expect(vaultAppSource).toContain('const activeNoteId = stateRef.current.vault.activeNoteId')
    expect(vaultAppSource).toContain('deletedVaultItemsContainNoteId(stateRef.current.vault.items, targetItemIds, activeNoteId)')
    expect(vaultAppSource).toContain('suppressActiveNoteTreeRevealForDeleteRef.current = activeNoteId')
    expect(vaultAppSource).toContain('pendingActiveNoteTreeRevealIdRef.current = \'\'')
  })

  it('lets workspace pointer activation cancel pending cursor restore before focusing an aisle', () => {
    expect(vaultAppSource).toContain('shouldClearPendingCursorRestoreForAisleActivation')
    expect(vaultAppSource).toContain('onActivateAisle={(editorKey, pointer) => {')
    expect(vaultAppSource).toContain('pendingCursorRestoreRef.current = null')
    expect(vaultAppSource).toContain('pendingFocusToAisleIdRef.current = null')
    expect(vaultAppSource).toContain('focusAtClientPoint: pointer')
    expect(vaultAppSource).toContain("source: 'pointer'")
  })

  it('starts newly created notes and folders in inline rename after revealing the sidebar tree', () => {
    expect(vaultAppSource).toContain('function revealVaultTreeForCreatedItem(')
    expect(vaultAppSource).toContain('sidebarCollapsed: false')
    expect(vaultAppSource).toContain('const createdRenameRef: { current: PendingCreatedTreeRename | null } = { current: null }')
    expect(vaultAppSource).toContain("createdRenameRef.current = {\n        kind: 'note',\n        itemId: result.noteId,")
    expect(vaultAppSource).toContain("createdRenameRef.current = {\n        kind: 'folder',\n        itemId: result.folderId,")
    expect(vaultAppSource).toContain('ui: revealVaultTreeForCreatedItem(result.state.ui, [parentFolderId])')
    expect(vaultAppSource).toContain('ui: revealVaultTreeForCreatedItem(result.state.ui, [parentFolderId, result.folderId])')
    expect(vaultAppSource).toContain("beginCreatedTreeRename(createdRename, 'Untitled')")
    expect(vaultAppSource).toContain("beginCreatedTreeRename(createdRename, 'Untitled folder')")
  })

  it('routes post-create rename focus only from Enter commits', () => {
    expect(vaultAppSource).toContain('const pendingCreatedTreeRenameRef = useRef<PendingCreatedTreeRename | null>(null)')
    expect(vaultAppSource).toContain('pendingCreatedEditRef.current = pending')
    expect(vaultAppSource).toContain("if (source !== 'enter') return")
    expect(vaultAppSource).toContain('pendingFocusToAisleIdRef.current = pending.aisleId')
    expect(vaultAppSource).toContain('pendingScrollToAisleIdRef.current = pending.aisleId')
    expect(vaultAppSource).toContain('pendingNavigationTopAisleIdRef.current = pending.aisleId')
    expect(vaultAppSource).toContain("focusIntent: 'aisle-activation'")
    expect(vaultAppSource).toContain("const returnNoteBodyId = activeVaultModel?.noteBody.id ?? ''")
    expect(vaultAppSource).toContain("const returnAisleId = activeVaultModel")
    expect(vaultAppSource).toContain('vaultEditors.activateAisleEditor(buildAisleEditorKey(pending.returnNoteBodyId, pending.returnAisleId), {')
    expect(vaultAppSource).toContain('focus: true')
    expect(vaultAppSource).toContain("source: 'programmatic'")
    expect(vaultAppSource).toContain('finishCreatedTreeRename(renamingTreeItemId, source)')
  })

  it('uses Tab during created item rename to create the next sibling of the same type', () => {
    expect(vaultAppSource).toContain('const skipTreeRenameBlurItemIdRef = useRef(\'\')')
    expect(vaultAppSource).toContain('createdRenameItemId={pendingCreatedTreeRenameRef.current?.itemId ?? \'\'}')
    expect(vaultAppSource).toContain('const tabCreatesNext = item.id === createdRenameItemId')
    expect(vaultAppSource).toContain("if (source === 'tab' && pendingCreatedRename) {")
    expect(vaultAppSource).toContain('const entry = findVaultItem(stateRef.current.vault.items, pendingCreatedRename.itemId)')
    expect(vaultAppSource).toContain('createNoteAt(entry.parentFolderId, entry.index + 1)')
    expect(vaultAppSource).toContain('createFolderAt(entry.parentFolderId, entry.index + 1)')
    expect(vaultAppSource).toContain("if (source === 'blur' && skipTreeRenameBlurItemIdRef.current === renamingTreeItemId)")
  })

  it('commits active rename drafts before shortcut-created items replace the inline edit state', () => {
    expect(vaultAppSource).toContain('const commitActiveTreeRenameBeforeCreate = useCallback(() => {')
    expect(vaultAppSource).toContain('renameItem(renamingTreeItemId, treeRenameDraft)')
    expect(vaultAppSource).toContain('pendingCreatedTreeRenameRef.current?.itemId === renamingTreeItemId')
    expect(vaultAppSource).toContain('skipTreeRenameBlurItemIdRef.current = renamingTreeItemId')
    expect(vaultAppSource).toContain('commitActiveTreeRenameBeforeCreate()')
    expect(vaultAppSource).toContain('}, [commitActiveTreeRenameBeforeCreate, createNoteAt])')
    expect(vaultAppSource).toContain('}, [commitActiveTreeRenameBeforeCreate, createFolderAt])')
  })

  it('wires note and folder sidebar context menus with reveal, rename, and delete actions', () => {
    const treeContextMenuSource = vaultAppSource.slice(
      vaultAppSource.indexOf('function VaultTreeContextMenu'),
      vaultAppSource.indexOf('function TreeItemRow'),
    )
    const sortLabelIndex = treeContextMenuSource.indexOf('label="Sort"')
    const renameLabelIndex = treeContextMenuSource.indexOf('>\n            Rename\n')
    expect(vaultAppSource).toContain('function VaultTreeContextMenu')
    expect(vaultAppSource).toContain('getVaultSidebarRevealLabel')
    expect(vaultAppSource).toContain('onCreateNote: () => void')
    expect(vaultAppSource).toContain('onCreateFolder: () => void')
    expect(vaultAppSource).toContain('onSort: (sortMode: TabSortMode) => void')
    expect(vaultAppSource).toContain("const getTreeContextCreateTarget = useCallback((): { parentFolderId: string | null; index: number } | null => {")
    expect(vaultAppSource).toContain("if (treeContextMenu.kind === 'root') {")
    expect(vaultAppSource).toContain("if (entry.item.type === 'folder') {")
    expect(vaultAppSource).toContain('parentFolderId: entry.item.id')
    expect(vaultAppSource).toContain('index: entry.item.children.length')
    expect(vaultAppSource).toContain('parentFolderId: entry.parentFolderId')
    expect(vaultAppSource).toContain('index: entry.index + 1')
    expect(vaultAppSource).toContain('createNoteAt(target.parentFolderId, target.index)')
    expect(vaultAppSource).toContain('createFolderAt(target.parentFolderId, target.index)')
    expect(vaultAppSource).toContain('New note')
    expect(vaultAppSource).toContain('New folder')
    expect(vaultAppSource).toContain('Sort')
    expect(vaultAppSource).toContain('Reveal in Finder')
    expect(vaultAppSource).toContain('Show in File Explorer')
    expect(vaultAppSource).toContain("return deleteNoteCount > 1 ? 'Delete notes' : 'Delete note'")
    expect(vaultAppSource).toContain('deleteLabel={treeContextDeleteLabel}')
    expect(vaultAppSource).toContain("deleteItems(treeContextMenu.itemType === 'note' ? treeContextDeleteNoteIds : [treeContextMenu.itemId])")
    expect(vaultAppSource).toContain('onContextMenu={(event) => {')
    expect(vaultAppSource).toContain('revealVaultItemLocation(payload)')
    expect(vaultAppSource).toContain("trigger: 'vault-sidebar-reveal-item'")
    expect(vaultAppSource).toContain('const latest = getLatestVaultStateFromMountedEditors()')
    expect(vaultAppSource).toContain('pendingEditorCount: latest.pendingEditorCount')
    expect(treeContextMenuSource.indexOf('New note')).toBeLessThan(treeContextMenuSource.indexOf('New folder'))
    expect(treeContextMenuSource.indexOf('New folder')).toBeLessThan(sortLabelIndex)
    expect(sortLabelIndex).toBeLessThan(renameLabelIndex)
    expect(renameLabelIndex).toBeLessThan(treeContextMenuSource.indexOf('{deleteLabel}'))
    expect(treeContextMenuSource.indexOf('{deleteLabel}')).toBeLessThan(treeContextMenuSource.indexOf('{revealLabel}'))
  })

  it('wires root sidebar context menus and non-recursive sort actions', () => {
    expect(vaultAppSource).toContain("kind: 'root'")
    expect(vaultAppSource).toContain("kind: 'item'")
    expect(vaultAppSource).toContain('onContextMenu={openRootTreeContextMenu}')
    expect(vaultAppSource).toContain("target?.closest('.vault-tree-row, .tab-context-menu')")
    expect(vaultAppSource).toContain('const VAULT_TREE_SORT_OPTIONS: Array<{ id: TabSortMode; label: string }> = [')
    expect(vaultAppSource).toContain("Name ascending")
    expect(vaultAppSource).toContain("Name descending")
    expect(vaultAppSource).toContain("Modified ascending")
    expect(vaultAppSource).toContain("Modified descending")
    expect(vaultAppSource).toContain("Created ascending")
    expect(vaultAppSource).toContain("Created descending")
    expect(vaultAppSource).toContain('const sortTreeContextScope = useCallback((sortMode: TabSortMode) => {')
    expect(vaultAppSource).toContain('vaultEditors.getMountedEditorMarkdownSnapshots()')
    expect(vaultAppSource).toContain('applyVaultEditorMarkdownSnapshotsToState(previous, snapshots)')
    expect(vaultAppSource).toContain('sortVaultItemsInScope(')
    expect(vaultAppSource).toContain('snapshotState.noteBodies')
  })

  it('exposes native vault item reveal for sidebar file locations', () => {
    expect(electronApiSource).toContain('revealVaultItemLocation?:')
    expect(preloadSource).toContain("revealVaultItemLocation: (payload) => ipcRenderer.invoke('reveal-vault-item-location', payload)")
    expect(ipcStorageSource).toContain("ipcMain.handle?.('reveal-vault-item-location'")
  })

  it('registers sidebar file tree icons in the shared app icon set', () => {
    expect(iconSource).toContain("'folder'")
    expect(iconSource).toContain("'folderOpen'")
    expect(iconSource).toContain("'filePlus'")
    expect(iconSource).toContain("'folderPlus'")
    expect(iconSource).not.toContain("'chevronRight'")
    expect(iconSource).not.toContain("'chevronDown'")
    expect(iconSource).not.toContain("'fileText'")
    expect(iconSource).toContain('M20 20a2 2 0 0 0 2-2V8')
    expect(iconSource).toContain('m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20')
    expect(iconSource).toContain('M6 22a2 2 0 0 1-2-2V4')
    expect(iconSource).toContain('M12 10v6')
  })
})
