import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = readFileSync(new URL('./VaultApp.tsx', import.meta.url), 'utf8')
const appCss = readFileSync(new URL('../App.css', import.meta.url), 'utf8')
const baseCss = readFileSync(new URL('../styles/base.css', import.meta.url), 'utf8')
const toastsCss = readFileSync(new URL('../styles/toasts.css', import.meta.url), 'utf8')

describe('VaultApp editable asset tools', () => {
  it('closes editable asset tool overlays only when the active note changes', () => {
    expect(source).toContain("const previousAssetToolsNoteLocationKeyRef = useRef('')")
    expect(source).toMatch(
      /useEffect\(\(\) => {\s*if \(previousAssetToolsNoteLocationKeyRef\.current === activeNoteLocationKey\) return\s*previousAssetToolsNoteLocationKeyRef\.current = activeNoteLocationKey\s*imageToolsController\.close\(\)\s*mediaToolsController\.close\(\)\s*}, \[activeNoteLocationKey, imageToolsController, mediaToolsController\]\)/,
    )
  })
})

describe('VaultApp aisle caps', () => {
  it('guards direct aisle insertion by active editor model', () => {
    expect(source).toContain('MAX_SCRATCHPAD_AISLES')
    expect(source).toContain('MAX_SCRATCHPAD_AISLE_WARNING_MESSAGE')
    expect(source).toContain('function getMaxAislesForEditorModel(model: ActiveEditorModel): number')
    expect(source).toContain("return model.kind === 'scratchpad' ? MAX_SCRATCHPAD_AISLES : MAX_NOTE_AISLES")
    expect(source).toContain('const maxAisles = getMaxAislesForEditorModel(activeModel)')
    expect(source).toContain('if (body.aisles.length >= maxAisles)')
    expect(source).toContain('window.alert(blockedMessage)')
    expect(source).toContain('bottomAisleControls=')
    expect(source).toContain('onDeleteAisle: deleteScratchpadAisle')
  })
})

describe('VaultApp frontmatter modal routing', () => {
  it('blocks structured frontmatter editing when stored YAML is invalid', () => {
    expect(source).toContain("body?.frontmatterStatus === 'invalid'")
    expect(source).toContain('Frontmatter YAML is invalid. Fix the markdown block before using the structured frontmatter editor.')
  })

  it('keeps note frontmatter editor sessions transient and keyed by active note', () => {
    expect(source).toContain('const [frontmatterModalSessions, setFrontmatterModalSessions] = useState<Record<string, VaultFrontmatterModalState>>({})')
    expect(source).toContain('const visibleFrontmatterModal =')
    expect(source).toContain('frontmatterModalSessions[activeModel.noteId] ?? null')
    expect(source).toContain('[modal.location.noteId]: modal')
    expect(source).toContain('closeFrontmatterModalSession(modal.location.noteId)')
    expect(source).toContain('setFrontmatterModalSessions({})')
    expect(source).not.toContain('const [frontmatterModal, setFrontmatterModal]')
  })

  it('renders note modals through the note workspace overlay instead of the app root', () => {
    expect(source).toContain('const noteWorkspaceOverlay = activeModel ? (')
    expect(source).toContain('modal={visibleFrontmatterModal}')
    expect(source).toContain('noteContentOverlay={noteWorkspaceOverlay}')
    expect(source).not.toContain('modal={frontmatterModal}')
    expect(source).not.toContain('open={aisleEditModalOpen && Boolean(activeModel)}')
  })

  it('includes fixed list controls for template settings and note rows', () => {
    expect(source).toContain('aria-label="frontmatter fixed list values"')
    expect(source).toContain('aria-label="frontmatter fixed list default values"')
    expect(source).toContain('frontmatter-fixed-list-choice')
    expect(source).not.toContain('<option value="">no options</option>')
  })

  it('reuses existing frontmatter values when selecting a template for an aisle', () => {
    expect(source).toContain('const selectFrontmatterTemplate = useCallback')
    expect(source).toContain('includeExisting: true')
    expect(source).not.toContain('includeExisting: false')
  })

  it('clears suggested template rows when selecting no template without clearing saved aisle frontmatter', () => {
    expect(source).toContain('const savedFrontmatterExists = hasFrontmatterDataForAisle(state, modal.noteBodyId, modal.aisleBodyId)')
    expect(source).toContain('rows: savedFrontmatterExists ? makeFrontmatterRowsManual(modal.rows) : []')
    expect(source).not.toContain('Suggested from')
    expect(source).not.toContain('These rows are not saved on this aisle yet.')
  })

  it('prompts for template field removals only when used derived rows are affected', () => {
    expect(source).toContain('getFrontmatterTemplateFieldRemovalUsage(stateRef.current, nextFrontmatter)')
    expect(source).toContain('setFrontmatterTemplateFieldRemovalDecision({ nextFrontmatter, usage })')
    expect(source).toContain('propagateFrontmatterTemplateChangesInState(previous, nextFrontmatter)')
    expect(source).toContain('FrontmatterTemplateFieldRemovalDecisionDialog')
    expect(source).toContain('Keep rows in notes')
    expect(source).toContain('Delete from notes')
    expect(source).toMatch(
      /<button type="button" className="vault-settings-action" onClick=\{onDeleteValues\}>\s*Delete from notes\s*<\/button>\s*<button type="button" className="vault-settings-action modal-primary-btn" onClick=\{onKeepValues\}>\s*Keep rows in notes\s*<\/button>/,
    )
    expect(source).toContain('materializeRemovedTemplateFieldValuesInState(previous, nextFrontmatter)')
    expect(source).toContain('removeRemovedTemplateFieldValuesInState(previous, nextFrontmatter)')
    expect(source).toContain('previous.frontmatter')
  })

  it('routes frontmatter modal text import/copy while keeping ordinary paste safe', () => {
    expect(source).toContain("from '../frontmatter/frontmatter-clipboard'")
    expect(source).toContain('parseFrontmatterImportData,')
    expect(source).toContain('const importFrontmatterTextToModal = useCallback')
    expect(source).toContain('const parsed = parseFrontmatterImportData(raw)')
    expect(source).toContain("return 'No frontmatter fields found.'")
    expect(source).toContain('templateId: null')
    expect(source).toContain('templateDerived: false')
    expect(source).toContain('buildFrontmatterModalDraftForAisle(')
    expect(source).toContain('frontmatter-note-import-textarea')
    expect(source).toContain('This will replace the current frontmatter rows.')
    expect(source).toContain('const copyFrontmatterFromModal = useCallback')
    expect(source).toContain('disableInvalidComputedFrontmatterRows(modal.rows)')
    expect(source).toContain('buildFrontmatterClipboardPayload(result.frontmatter')
    expect(source).toContain('writeFrontmatterClipboardPayload(')
    expect(source).toContain('function isFrontmatterModalDirtyAgainstSavedDraft(')
    expect(source).toContain('const visibleFrontmatterModalDirty = Boolean(')
    expect(source).toContain('hasUnsavedChanges={visibleFrontmatterModalDirty}')
    expect(source).toContain('aria-disabled={hasUnsavedChanges ? \'true\' : undefined}')
    expect(source).toContain('onCopyBlocked={() => pushAppToast(\'Save changes before copying frontmatter.\', \'warning\')}')
    expect(source).toContain('onClick={() => saveFrontmatter({ close: false })}')
    expect(source).toContain('onClick={() => saveFrontmatter({ close: true })}')
    expect(source).toContain('frontmatter-note-unsaved-status')
    expect(source).toContain('onImportFrontmatterText={importFrontmatterTextToModal}')
    expect(source).toContain('onCopyFrontmatter={copyFrontmatterFromModal}')
    expect(source).not.toContain('const applyFrontmatterClipboardPaste = useCallback')
    expect(source).not.toContain('const pasteFrontmatterClipboard = useCallback')
    expect(source).not.toContain('buildFrontmatterClipboardPasteForAisle(')
    expect(source).not.toContain('readFrontmatterClipboardPayloadFromNavigator(undefined, { allowYamlFallback: false })')
    expect(source).not.toContain('onFrontmatterPaste:')
    expect(source).not.toContain('onPasteFrontmatter=')
  })

  it('records focused frontmatter timing diagnostics without logging field values', () => {
    expect(source).toContain('const VAULT_FRONTMATTER_TIMING_DIAGNOSTIC_THRESHOLD_MS = 16')
    expect(source).toContain('function recordVaultFrontmatterTiming(')
    expect(source).toContain("recordDiagnosticEvent('frontmatter', event")
    expect(source).toContain("'frontmatter-text-import'")
    expect(source).toContain("'frontmatter-clipboard-copy'")
    expect(source).toContain("'frontmatter-save'")
    expect(source).toContain('rowCount: modal.rows.length')
    expect(source).toContain('warningCount,')
    expect(source).not.toContain('frontmatter: result.frontmatter')
  })
})

describe('VaultApp diagnostics and notification wiring', () => {
  it('wires diagnostic logging, heartbeat, log reading, and MessagesView controls', () => {
    expect(source).toContain('configureDiagnosticLogging,')
    expect(source).toContain('createMainThreadHeartbeat,')
    expect(source).toContain('deleteAllDiagnosticLogs as deleteAllStoredDiagnosticLogs,')
    expect(source).toContain('deleteDiagnosticLogDay,')
    expect(source).toContain('listDiagnosticLogDays,')
    expect(source).toContain('readDiagnosticLogEntries,')
    expect(source).toContain('subscribeDiagnosticLogChanges,')
    expect(source).toContain('const [diagnosticDays, setDiagnosticDays] = useState<string[]>([])')
    expect(source).toContain('const [diagnosticCaptureEnabled, setDiagnosticCaptureEnabled] = useState(true)')
    expect(source).toContain('const loadDiagnosticDays = useCallback')
    expect(source).toContain('void readDiagnosticLogEntries(selectedDiagnosticDay)')
    expect(source).toContain('subscribeDiagnosticLogChanges((entry) => {')
    expect(source).toContain('const heartbeat = createMainThreadHeartbeat()')
    expect(source).toContain('configureDiagnosticLogging(')
    expect(source).toContain('mountedEditorCount: diagnosticMountedEditorCount')
    expect(source).toContain('openTabCount: state.vault.openTabs?.length ?? 0')
    expect(source).toContain('messagesSection,')
    expect(source).toContain('diagnosticDays={diagnosticDays}')
    expect(source).toContain('diagnosticEntries={diagnosticEntries}')
    expect(source).toContain('diagnosticCaptureEnabled={diagnosticCaptureEnabled}')
    expect(source).toContain('onDiagnosticCaptureEnabledChange={setDiagnosticCaptureEnabled}')
    expect(source).toContain('onOpenDiagnosticsFolder={')
    expect(source).toContain('onDeleteTodayDiagnosticLogs={deleteTodayDiagnosticLogs}')
    expect(source).toContain('onDeleteAllDiagnosticLogs={deleteAllDiagnosticLogs}')
    expect(source).toContain('canDeleteTodayDiagnosticLogs={diagnosticDays.includes(getDiagnosticDayKey())}')
  })

  it('wires the app notification hook, hosts, and toast history path', () => {
    expect(source).toContain("import { useAppNotifications } from './useAppNotifications'")
    expect(source).toContain("import { ToastHost } from '../components/overlays/ToastHost'")
    expect(source).toContain("import { TipHost } from '../components/overlays/TipHost'")
    expect(source).toContain('const appNotifications = useAppNotifications({')
    expect(source).toContain('const pushAppToast = useCallback')
    expect(source).toContain('pushToast: pushAppToast')
    expect(source).toContain('const pushEditorToolToast = pushAppToast')
    expect(source).toContain('const pushStorageToast = pushAppToast')
    expect(source).toContain('<ToastHost')
    expect(source).toContain('toasts={appNotifications.toasts}')
    expect(source).toContain('<TipHost tips={appNotifications.visibleTipDefinitions} onDismissTip={appNotifications.dismissTip} />')
    expect(source).toContain('toastHistory={state.toastHistory ?? []}')
    expect(source).not.toContain("pushAppToast(warningMessages.join('\\n'), 'warning', 9000)")
    expect(source).not.toContain('const pushEditorToolToast = useCallback((message: string, tone?: ToastTone) => {')
    expect(source).not.toContain('const pushStorageToast = useCallback((message: string, tone?: ToastTone) => {')
  })
})

describe('VaultApp scratchpad/settings navigation', () => {
  it('routes the scratchpad toggle through settings-preserving navigation state', () => {
    expect(source).toContain("import { getNextNotesScratchpadToggleState } from '../navigation/toggle-notes-scratchpad'")
    expect(source).toContain("const viewModeRef = useRef<ViewMode>('main')")
    expect(source).toContain('const nextToggleState = getNextNotesScratchpadToggleState({')
    expect(source).toContain('viewMode: viewModeRef.current,')
    expect(source).toContain('scratchpadActive: currentScratchpadActive,')
    expect(source).toContain('viewModeRef.current = nextToggleState.viewMode')
    expect(source).toContain('scratchpadActiveRef.current = nextToggleState.scratchpadActive')
    expect(source).toContain('setViewMode(nextToggleState.viewMode)')
    expect(source).toContain('if (!nextToggleState.scratchpadActive) {')
    expect(source).toContain("const scratchpadToggleLabel = viewMode === 'settings'")
    expect(source).toContain("? 'Return to scratchpad'")
    expect(source).toContain(": 'Show scratchpad'")
    expect(source).toContain('aria-label={scratchpadToggleLabel}')
  })
})

describe('VaultApp sidebar search wiring', () => {
  it('routes metadata filter actions into the sidebar search panel', () => {
    expect(source).toContain('SidebarSearchPanel')
    expect(source).toContain('const [sidebarSearchMode, setSidebarSearchMode] = useState(false)')
    expect(source).toContain('const sidebarSearchVisible = sidebarSearchMode')
    expect(source).toContain("const vaultTreeFilterQuery = sidebarSearchVisible ? query : ''")
    expect(source).toContain('className={`vault-icon-button vault-sidebar-search-mode-toggle ${')
    expect(source).toContain('aria-label="Search notes"')
    expect(source).toContain('const toggleSidebarSearchModeFromButton = useCallback')
    expect(source).toContain('if (sidebarSearchVisible) {')
    expect(source).toContain('onClick={toggleSidebarSearchModeFromButton}')
    expect(source.match(/closeSidebarSearchMode\(\)/g)?.length).toBeGreaterThanOrEqual(3)
    expect(source).toContain('onCloseMode={closeSidebarSearchMode}')
    expect(source).toContain('onClearButtonClick={clearSidebarSearch}')
    expect(source).toContain("activeNoteId={activeModelIsScratchpad ? '' : state.vault.activeNoteId}")
    expect(source).toContain("activeAisleId={activeModelIsScratchpad ? '' : renderedActiveAisleId}")
    expect(source).toContain('completeSidebarSearchTokenQuery(current, tokenText)')
    expect(source).toContain('getSidebarSearchTokenForKey(sidebarSearchIndexes, kind, key)')
    expect(source).toContain('metadataSearchActive={sidebarSearchMetadataActive}')
    expect(source).toContain('parsedSidebarSearch.presenceTerms.length > 0')
    expect(source).not.toContain("tokenText: 'tag:true'")
    expect(source).not.toContain("tokenText: 'tag:false'")
    expect(source).not.toContain("tokenText: 'fm:true'")
    expect(source).not.toContain("tokenText: 'fm:false'")
    expect(source).not.toContain("tokenText: 'synced:true'")
    expect(source).not.toContain("tokenText: 'synced:false'")
    expect(source).not.toContain("tokenText: 'duplicate:true'")
    expect(source).not.toContain("tokenText: 'duplicate:false'")
    expect(source).toContain('searchHistory={sidebarSearchHistory}')
    expect(source).toContain("const SIDEBAR_SEARCH_DISPLAY_STORAGE_KEY = 'aislenote:sidebar-search-display:v1'")
    expect(source).toContain('const [sidebarSearchDisplaySettings, setSidebarSearchDisplaySettings] = useState(loadSidebarSearchDisplaySettings)')
    expect(source).toContain('showFolderNames={sidebarSearchDisplaySettings.showFolderNames}')
    expect(source).toContain('showAisleMatches={sidebarSearchDisplaySettings.showAisleMatches}')
    expect(source).toContain('onShowFolderNamesChange={setSidebarSearchShowFolderNames}')
    expect(source).toContain('onShowAisleMatchesChange={setSidebarSearchShowAisleMatches}')
    expect(source).toContain('onSelectSearchOption={selectSidebarSearchOption}')
    expect(source).toContain('onSelectHistory={selectSidebarSearchHistory}')
    expect(source).toContain('onClearHistory={clearSidebarSearchHistory}')
    expect(source).toContain('recordSidebarSearchHistory(query)')
    expect(source).toContain('type SidebarSearchResultOpenMode,')
    expect(source).toContain('result: SidebarSearchResult, mode?: SidebarSearchResultOpenMode')
    expect(source).toContain("mode === 'retained' ? { tabDisposition: 'retained' } : undefined")
    expect(source).toContain("activateSidebarSearchKey('synced', key)")
    expect(source).toContain("activateSidebarSearchKey('tags', key)")
    expect(source).toContain("activateSidebarSearchKey('frontmatter', getFrontmatterTemplateFilterKey(templateId))")
    expect(source).toContain('onOpenTagFilter={filterTag}')
    expect(source).toContain('onFilterTemplate={filterFrontmatterTemplateFromModal}')
    expect(source).not.toContain('vault-sidebar-search-toggle')
    expect(source).not.toContain('frontmatterTemplateFilterAisleIds={frontmatterTemplateFilterAisleIds}')
    expect(source).not.toContain('onFilterAisleFrontmatterTemplate={filterAisleFrontmatterTemplate}')
  })
})

describe('VaultApp sidebar resize handle', () => {
  it('uses an explicit capsule handle with double-click reset', () => {
    expect(source).toContain('const resetSidebarWidth = useCallback')
    expect(source).toContain('sidebarWidth: clampSidebarWidth(DEFAULT_UI_SETTINGS.sidebarWidth)')
    expect(source).toContain('className="vault-sidebar-resize-handle"')
    expect(source).toContain('data-app-tooltip="Drag to resize. Double click to reset."')
    expect(source).toContain('onDoubleClick={resetSidebarWidth}')
    expect(source).toContain('className="vault-sidebar-resize-capsule"')
    expect(source).toContain('const [observedVaultTopbarHeight, setObservedVaultTopbarHeight] = useState(0)')
    expect(source).toContain('const vaultShellRef = useRef<HTMLDivElement | null>(null)')
    expect(source).toContain('const updateObservedVaultTopbarHeight = useCallback')
    expect(source).toContain('readObservedVaultTopbarHeight(shell)')
    expect(source).toContain("shell.querySelector<HTMLElement>('.note-aisles-shell > .note-shared-toolbar .app-shared-editor-toolbar')")
    expect(source).toContain("'--vault-topbar-observed-height': `${observedVaultTopbarHeight}px`")
    expect(source).toContain('ref={vaultShellRef}')
    expect(source).toContain('function getFrontmatterNoteModalStyle(')
    expect(source).toContain("'--frontmatter-note-modal-left': `${left}px`")
    expect(source).toContain("'--frontmatter-note-modal-width': `${modalWidth}px`")
    expect(source).toContain('const [noteContentViewportRect, setNoteContentViewportRect] = useState<VaultNoteActionPickerViewportRect | null>(null)')
    expect(appCss).toContain('--vault-topbar-content-height: calc(')
    expect(appCss).toContain('--vault-topbar-observed-height: 0px;')
    expect(appCss).toContain('--vault-topbar-height: max(')
    expect(appCss).toContain('calc(var(--vault-topbar-content-height) + 1px),')
    expect(appCss).toContain('var(--vault-topbar-observed-height)')
    expect(appCss).toContain('--vault-sidebar-footer-height: calc(')
    expect(appCss).toContain('--note-tab-strip-height: var(--vault-sidebar-footer-height);')
    expect(appCss).toContain('--note-tab-font-size: 1rem;')
    expect(appCss).toContain('padding: var(--vault-sidebar-footer-block-padding) var(--vault-sidebar-control-inset-inline);')
    expect(appCss).toContain('--resize-handle-width: calc(1.4rem + 2px);')
    expect(appCss).toContain('--resize-handle-height: calc(4.4rem + 4px);')
    expect(appCss).toContain('--resize-handle-half-height: calc(2.2rem + 2px);')
    expect(appCss).toContain('--resize-handle-capsule-width: 0.34rem;')
    expect(appCss).toContain('--resize-handle-capsule-height: calc(3rem + 4px);')
    expect(appCss).toContain('--resize-handle-center-y: calc(var(--vault-topbar-height) + (100vh - var(--vault-topbar-height)) * 0.7);')
    expect(appCss).not.toContain('--sidebar-resize-handle-top')
    expect(appCss).toContain('.vault-sidebar {\n  flex: 0 0 auto;\n  position: relative;\n  z-index: 40;')
    expect(appCss).toContain('.vault-sidebar-header {\n  box-sizing: border-box;\n  display: flex;\n  align-items: flex-start;\n  gap: var(--vault-sidebar-control-gap);\n  min-height: var(--vault-topbar-height);')
    expect(appCss).toContain('.vault-shell .note-shared-toolbar.toastui-editor-toolbar {\n  --editor-toolbar-spacer-width: 0.55rem;\n  border-bottom: 1px solid var(--vault-topbar-border) !important;\n  min-height: var(--vault-topbar-height) !important;')
    expect(appCss).toContain('height: auto !important;\n  min-height: var(--vault-topbar-content-height) !important;\n  padding: var(--vault-topbar-block-padding) var(--vault-topbar-inline-padding) !important;')
    expect(appCss).toContain('top: 70px;')
    expect(appCss).toContain('max-height: calc(100% - 210px);')
    expect(appCss).toContain('transform: translateX(-50%);')
    expect(appCss).toContain('left: var(--frontmatter-note-modal-left, 50%);')
    expect(appCss).toContain('width: var(--frontmatter-note-modal-width, min(960px, calc(100% - 32px)));')
    expect(appCss).toContain('.vault-utility-header {\n  flex: 0 0 auto;\n  box-sizing: border-box;\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  gap: var(--vault-sidebar-control-gap);\n  min-height: var(--vault-topbar-height);')
    expect(appCss).toContain('.vault-sidebar-resize-handle {\n  position: absolute;\n  z-index: 6;\n  top: var(--resize-handle-center-y);')
    expect(appCss).toContain('border: 1px solid var(--note-aisle-resize-border);')
    expect(appCss).toContain('background: var(--note-aisle-resize-bg);')
    expect(appCss).toContain('background: var(--note-aisle-resize-hover-bg);')
    expect(appCss).toContain('outline: 2px solid var(--note-aisle-resize-focus-outline);')
    expect(appCss).toContain('.vault-sidebar-resize-capsule')
    expect(appCss).not.toContain('.vault-sidebar-resize-handle::before')
  })
})

describe('VaultApp zoom HUD', () => {
  it('shows native app zoom changes without using the toast stack', () => {
    expect(source).toContain('const [zoomHudPercent, setZoomHudPercent] = useState<number | null>(null)')
    expect(source).toContain('const zoomHudTimeoutRef = useRef<number | null>(null)')
    expect(source).toContain('window.electronAPI?.onAppZoomChanged?.((payload) => {')
    expect(source).toContain('setZoomHudPercent(Math.round(payload.percent))')
    expect(source).toContain('setZoomHudPercent(null)')
    expect(source).toContain('className="app-zoom-hud"')
    expect(appCss).toContain('.app-zoom-hud')
    expect(appCss).toContain('top: calc(var(--vault-topbar-height) + 0.65rem);')
    expect(appCss).toContain('@keyframes zoomHudFadeIn')
  })
})

describe('VaultApp tag autocomplete wiring', () => {
  it('connects editor tag autocomplete to the existing tag index and menu', () => {
    expect(source).toContain("import { TagAutocompleteMenu } from '../components/editor/TagAutocompleteMenu'")
    expect(source).toContain("import { useTagAutocompleteController } from '../tags/useTagAutocompleteController'")
    expect(source).toContain("const TAG_AUTOCOMPLETE_RECENT_STORAGE_KEY = 'aislenote:tag-autocomplete-recent:v1'")
    expect(source).toContain('const [tagAutocompleteRecentKeys, setTagAutocompleteRecentKeys] = useState(loadTagAutocompleteRecentKeys)')
    expect(source).toContain('const tagAutocompleteRefreshRef = useRef<(() => void) | null>(null)')
    expect(source).toContain('onTagAutocompleteQueryChange: refreshTagAutocompleteFromEditor')
    expect(source).toContain('const tagAutocompleteController = useTagAutocompleteController({')
    expect(source).toContain('getAvailableTags: () => tagAutocompleteFilterIndex.availableOptions')
    expect(source).toContain('commitActiveEditorMarkdownNow: vaultEditors.commitActiveEditorMarkdownNow')
    expect(source).toContain('tagAutocompleteRefreshRef.current = tagAutocompleteController.refreshQuery')
    expect(source).toContain('<TagAutocompleteMenu')
    expect(source).toContain('onChoose={tagAutocompleteController.acceptSuggestion}')
  })
})

describe('VaultApp heading collapse wiring', () => {
  it('persists heading collapse state through the vault editor hook', () => {
    expect(source).toContain("import { isHeadingCollapsed, setHeadingCollapsed } from '../editor/heading-collapse-state'")
    expect(source).toContain('const toggleHeadingCollapse = useCallback')
    expect(source).toContain('const nextCollapsed = !isHeadingCollapsed(previous.ui.headingCollapseState, noteBodyId, aisleId, headingKey)')
    expect(source).toContain('const nextHeadingCollapseState = setHeadingCollapsed(')
    expect(source).toContain('headingCollapseState: nextHeadingCollapseState')
    expect(source).toContain('const expandHeadingCollapse = useCallback')
    expect(source).toContain('headingKey,\n          false,')
    expect(source).toContain('headingCollapseState: state.ui.headingCollapseState')
    expect(source).toContain('onToggleHeadingCollapse: toggleHeadingCollapse')
    expect(source).toContain('onExpandHeadingCollapse: expandHeadingCollapse')
  })
})

describe('VaultApp large vault performance wiring', () => {
  it('builds sidebar search indexes from narrow vault index dependencies instead of whole app state', () => {
    expect(source).toContain("import { createVaultIndexContext } from '../filters/vault-index-context'")
    expect(source).toContain('const vaultIndexContext = useMemo(')
    expect(source).toContain('() => createVaultIndexContext(stateRef.current)')
    expect(source).toContain('state.vault.items')
    expect(source).toContain('state.noteBodies')
    expect(source).toContain('state.noteAisleBodies')
    expect(source).toContain('const sidebarSearchNeedsFullIndexes = sidebarSearchMode')
    expect(source).toContain("() => buildNoteFilterIndex(vaultIndexContext.state, 'tags', [], vaultIndexContext)")
    expect(source).toContain('return buildSidebarSearchIndexes(vaultIndexContext.state, vaultIndexContext)')
    expect(source).toContain('...getEmptySidebarSearchIndexes(),')
    expect(source).toContain('sidebarSearchMode\n        ? buildSidebarSearchResultGroups')
    expect(source).toContain('context: vaultIndexContext,')
    expect(source).not.toContain('const sidebarSearchIndexes = useMemo(() => buildSidebarSearchIndexes(state), [state])')
  })

  it('keeps theme CSS variables and active note resolution off whole-state dependencies', () => {
    expect(source).toContain('...getThemePaletteVariables({')
    expect(source).toContain('state.ui.themePalettes,')
    expect(source).toContain('state.ui.toolbarButtonScale,')
    expect(source).not.toContain('[defaultToolbarButtonScale, state]')
    expect(source).toContain('[state.noteAisleBodies, state.noteBodies, state.vault.activeNoteId, state.vault.items, stateRef]')
    expect(source).toContain('[state.noteAisleBodies, state.noteBodies, state.scratchpad, stateRef]')
  })

  it('flushes debounced editor changes before state-backed navigation, search, find, and storage reads', () => {
    expect(source).toContain('vaultEditors.flushPendingEditorAppStateCommit()')
    expect(source).toMatch(/const getLatestVaultStateFromMountedEditors = useCallback\(\(\) => {\s*vaultEditors\.flushPendingEditorAppStateCommit\(\)/)
    const navigationStart = source.indexOf('const applyVaultNavigationLocation = useCallback')
    const navigationEnd = source.indexOf('const selectNoteTab = useCallback', navigationStart)
    const navigationBody = source.slice(navigationStart, navigationEnd)
    expect(navigationBody).toContain('vaultEditors.flushPendingEditorAppStateCommit()')
    expect(navigationBody).toContain("recordVaultNavigationTiming('vault-navigation'")
    expect(source).toMatch(/const updateSidebarSearchQuery = useCallback\(\s*\(nextQuery: string\) => {\s*vaultEditors\.flushPendingEditorAppStateCommit\(\)/)
    expect(source).toMatch(/const updateFindReplaceQuery = useCallback\(\(nextQuery: string\) => {\s*vaultEditors\.flushPendingEditorAppStateCommit\(\)/)
  })

  it('applies vault history navigation without replacing temporary tabs', () => {
    expect(source).toContain('const applyVaultNavigationHistoryLocation = useCallback')
    expect(source).toContain("applyVaultNavigationLocation(location, { tabDisposition: 'preserve' })")
    const historyStart = source.indexOf('const { navigateVaultHistoryBy } = useVaultNavigationHistory')
    const historyEnd = source.indexOf('usePendingNoteCursorRestore', historyStart)
    const historyBody = source.slice(historyStart, historyEnd)
    expect(historyBody).toContain('onApplyLocation: applyVaultNavigationHistoryLocation')
    expect(historyBody).not.toContain('onApplyLocation: applyVaultNavigationLocation')
  })

  it('memoizes and virtualizes the sidebar tree over the large-vault threshold', () => {
    expect(source).toContain('const VAULT_TREE_VIRTUALIZATION_THRESHOLD = 300')
    expect(source).toContain('const VAULT_TREE_VIRTUAL_ROW_HEIGHT = 28')
    expect(source).toContain('function flattenVisibleVaultTreeRows(')
    expect(source).toContain('const MemoizedTreeItemRow = React.memo(TreeItemRow)')
    expect(source).toContain('const vaultTreeFlatRows = useMemo(')
    expect(source).toContain('const useVirtualizedVaultTree = vaultTreeFlatRows.length > VAULT_TREE_VIRTUALIZATION_THRESHOLD')
    expect(source).toContain('className="vault-tree-virtual-spacer"')
    expect(source).toContain('className="vault-tree-virtual-row"')
    expect(source).toContain('renderChildren={false}')
    expect(appCss).toContain('.vault-tree-virtual-spacer')
    expect(appCss).toContain('.vault-tree-virtual-row')
    expect(appCss).toContain('min-height: 28px;')
  })

  it('uses a local draft palette before debounced global theme commits', () => {
    expect(source).toContain('const [draftPalette, setDraftPalette] = useState(committedPalette)')
    expect(source).toContain('const paletteCommitTimerRef = useRef<number | null>(null)')
    expect(source).toContain('const scheduleThemePaletteCommit = (themeId: AppTheme, palette: typeof committedPalette) => {')
    expect(source).toContain('paletteCommitTimerRef.current = window.setTimeout(() => {')
    expect(source).toContain('setDraftPalette(nextPalette)')
    expect(source).toContain('scheduleThemePaletteCommit(themeId, nextPalette)')
    expect(source).toContain('onPreviewChange={(value) => updatePaletteSlot(slot, value)}')
    expect(source).toContain('onCommit={(value) => commitPaletteSlot(slot, value)}')
  })

  it('keeps closed note tab history transient and wires reopen through navigation', () => {
    expect(source).toContain('const CLOSED_NOTE_TAB_HISTORY_LIMIT = 20')
    expect(source).toContain('const closedNoteTabHistoryRef = useRef<ClosedVaultTab[]>([])')
    expect(source).toContain('const closedTab = getClosedVaultTab(snapshotState.vault, noteId)')
    expect(source).toContain('rememberClosedNoteTab(closedTab)')
    expect(source).toContain('{ restoreClosedTab: closedTab }')
    expect(source).toContain('restoreClosedVaultTab(previousWithCursor.vault, options.restoreClosedTab)')
    expect(source).toContain('reopenClosedNoteTab,')
  })
})

describe('VaultApp find replace wiring', () => {
  it('keeps keyboard note find available while shifted find and the toolbar magnifier open notes search', () => {
    expect(source).toContain("import { FindReplacePanel } from '../components/editor/FindReplacePanel'")
    expect(source).toContain("import { getSearchShortcutTarget } from '../components/editor/find-replace-shortcuts'")
    expect(source).toContain('const [findReplaceOpen, setFindReplaceOpen] = useState(false)')
    expect(source).toContain('const findReplaceMatches = useMemo')
    expect(source).toContain('findVisibleMatches(')
    expect(source).toContain("      'note',\n      findReplaceQuery,")
    expect(source).toContain('if (editor) vaultEditors.commitActiveEditorMarkdownNow(editor)')
    expect(source).toContain('const openFindReplace = useCallback')
    expect(source).toContain('const target = getSearchShortcutTarget(event, isMacPlatform)')
    expect(source).toContain('if (!target) return')
    expect(source).toMatch(/if \(target === 'sidebar'\) {\s*focusNotesFilter\(\)\s*return\s*}\s*openFindReplace\(\)/)
    expect(source).toContain('onOpenFindReplace={focusNotesFilter}')
    expect(source).toContain('setFindReplaceOpen(false)')
    expect(source).toContain('<FindReplacePanel')
    expect(source).not.toContain('replaceMode={findReplaceMode')
    expect(source).not.toContain('scope={findReplaceScope}')
    expect(source).not.toContain('vault-sidebar-search-toggle')
    expect(source).not.toContain('onOpenFindReplace={() => undefined}')
  })
})

describe('VaultApp vault manager wiring', () => {
  it('centralizes transient menu cleanup for settings and active-note navigation', () => {
    expect(source).toContain('const closeTransientFloatingUi = useCallback(() => {')
    expect(source).toContain("setOpenVaultActionMenuKey('')")
    expect(source).toContain('setVaultSwitcherOpen(false)')
    expect(source).toContain('setAisleEditModalOpen(false)')
    expect(source).toContain('closeTransientFloatingUi()')
    expect(source).toMatch(/const openUtilityView = useCallback\(\(targetViewMode: UtilityViewMode = 'settings'\) => {\s*closeTransientFloatingUi\(\)\s*setAisleEditModalOpen\(false\)\s*setViewMode\(targetViewMode\)/)
  })

  it('renames the Data storage tab to Vaults while keeping the storage section id', () => {
    expect(source).toContain("{ id: 'storage', label: 'Vaults' }")
    expect(source).toContain("setDataSettingsSection('storage')")
    expect(source).not.toContain("{ id: 'storage', label: 'Storage' }")
  })

  it('renders the inline vault manager instead of the old storage summary card', () => {
    expect(source).toContain('const renderVaultManager = () => {')
    expect(source).toContain('useStorageProfileController({')
    expect(source).toContain('beforeStorageAction: commitVaultBeforeStorageAction')
    expect(source).toContain('commitAppStateNow(latest.state, {')
    expect(source).toContain('New Vault')
    expect(source).toContain('function VaultNameDialog({')
    expect(source).toContain("const actionLabel = dialog.mode === 'create' ? 'Choose location' : 'Rename'")
    expect(source).toContain('<footer className="modal-card-footer modal-card-split-actions">')
    expect(source).toContain('className="modal-card-primary-actions"')
    expect(source).toMatch(/<button type="button" className="vault-settings-action" onClick=\{onCancel\}>\s*Cancel\s*<\/button>\s*<div className="modal-card-primary-actions">\s*<button type="submit" className="vault-settings-action" disabled=\{!canSubmit\}>\s*\{actionLabel\}\s*<\/button>/)
    expect(source).toContain("setVaultNameDialog({ mode: 'create', initialName: 'New Vault' })")
    expect(source).toContain("setVaultNameDialog({ mode: 'rename', initialName: vault.vaultName, vault })")
    expect(source).toContain('<VaultNameDialog')
    expect(source).toContain('storageProfileController.chooseVaultLocation()')
    expect(source).toContain('storageProfileController.createVault({ name, locationPath })')
    expect(source).toContain('const renameVaultFromSettings = useCallback((vault: KnownVault) => {')
    expect(source).toContain('storageProfileController.renameVault(name, getVaultSelector(dialog.vault))')
    expect(source).toContain('vaultId: storageProfileStatus.activeVaultId ?? undefined,')
    expect(source).toContain('onClick={() => renameVaultFromSettings(vault)}')
    expect(source).toContain('aria-label="Vaults"')
    expect(source).toContain('<span>Vaults</span>')
    expect(source).toContain('<span className="vault-manager-eyebrow">Current vault</span>')
    expect(source).not.toContain('Remembered vaults')
    expect(source).not.toContain("<small>{vault.isActive ? 'current vault' : vault.available ? vault.vaultPath : 'folder missing'}</small>")
    expect(source).toContain('iconId="ellipsisVertical"')
    expect(source).toContain('runCurrentVaultAction(() => void storageProfileController.moveStorageProfile())')
    expect(source).toContain('runCurrentVaultAction(() => void storageProfileController.revealStorageProfile())')
    expect(source).toContain('Remove from List')
    expect(source).toContain('Delete Vault')
    expect(source).toContain('desktopVaultSetupRequired')
    expect(source).toContain('const renderVaultSetupScreen = () => (')
    expect(source).toContain("const VAULT_SETUP_APP_NAME = 'AisleNote'")
    expect(source).toContain("const VAULT_SETUP_LOGO_SRC = './favicon.svg'")
    expect(source).toContain('runtimeVersionLabel')
    expect(source).toContain('Create new vault')
    expect(source).toContain('Name a vault, then choose where to save it.')
    expect(source).toContain('Open AisleNote vault')
    expect(source).toContain('Choose an existing AisleNote vault.')
    expect(appCss).toContain('.vault-frontmatter-modal.vault-name-modal')
    expect(appCss).toContain('.vault-frontmatter-modal .modal-card-footer.modal-card-split-actions')
    expect(appCss).toContain('.vault-frontmatter-modal .modal-card-primary-actions')
    expect(source).not.toContain('window.prompt(')
    expect(source).not.toContain('Open Vault Folder')
    expect(source).not.toContain('renameCurrentVaultFromSettings')
    expect(source).not.toContain('vault-manager-meta-grid')
    expect(appCss).not.toContain('vault-manager-meta-grid')
    expect(source).not.toContain('<span>status</span>')
    expect(source).not.toContain('<span>health</span>')
    expect(source).not.toContain('<span>writable</span>')
    expect(source).not.toContain('<span>schema</span>')
    expect(source).not.toContain('void storageProfileController.createVault()')
    expect(source).not.toContain('storageProfileController.renameVault(name, vault ? getVaultSelector(vault) : undefined)')
    expect(source).not.toContain('Create a new vault under a folder.')
    expect(source).not.toContain('Create or open a vault')
    expect(source).not.toContain('Put that folder in iCloud, Dropbox, OneDrive')
    expect(source).not.toContain('listSearchableNoteLocations(state).length.toLocaleString()')
    expect(source).not.toContain('serializedState: getSerializedStateForStorageAction')
  })

  it('renders a bottom sidebar vault switcher through the storage controller', () => {
    const sidebarFooterStart = source.indexOf('const renderSidebarVaultFooter = () => {')
    const sidebarFooter = source.slice(sidebarFooterStart, source.indexOf('const renderDataSettings', sidebarFooterStart))
    expect(source).toContain('function getVaultRowsFromStorageStatus(storageProfileStatus: StorageProfileStatus | null): KnownVault[]')
    expect(source).toContain('const [vaultSwitcherOpen, setVaultSwitcherOpen] = useState(false)')
    expect(source).toContain('const switchVaultFromSidebar = useCallback((vault: KnownVault) => {')
    expect(source).toContain('void storageProfileController.switchVault(getVaultSelector(vault))')
    expect(source).toContain('const openVaultFromSidebar = useCallback(() => {')
    expect(source).toContain('void storageProfileController.openVault()')
    expect(source).toContain('const createVaultFromSidebar = useCallback(() => {')
    expect(source).toContain('createVaultFromSettings()')
    expect(source).toContain('const toggleSidebarCollapsed = useCallback(() => {')
    expect(source).toContain('const renderSidebarVaultFooter = () => {')
    expect(source).toContain('className="vault-sidebar-switcher-trigger"')
    expect(source).toContain('aria-label="Vault switcher"')
    expect(source).toContain('onClick={() => switchVaultFromSidebar(vault)}')
    expect(source).toContain('onClick={toggleSidebarCollapsed}')
    expect(source).toContain('{renderSidebarVaultFooter()}')
    expect(sidebarFooter).toContain('{vaultFoldersAvailable && vaultSwitcherOpen ? (')
    expect(sidebarFooter).toContain('<AppIcon iconId="minimize" className="vault-sidebar-switcher-chevron" />')
    expect(sidebarFooter).not.toContain("vaultSwitcherOpen ? 'minimize' : 'maximize'")
    expect(sidebarFooter).toContain('<span className="vault-sidebar-switcher-row-name">{vault.vaultName}</span>')
    expect(sidebarFooter).toContain('<AppIcon iconId="folderOpen" className="vault-sidebar-switcher-row-icon" />')
    expect(sidebarFooter).toContain('className="vault-sidebar-switcher-actions"')
    expect(sidebarFooter).toContain('<span>Open Vault</span>')
    expect(sidebarFooter).toContain('className="vault-sidebar-switcher-new"')
    expect(sidebarFooter).toContain('<AppIcon iconId="plus" className="vault-sidebar-switcher-row-icon" />')
    expect(sidebarFooter).toContain('<span>New Vault</span>')
    expect(sidebarFooter).not.toContain('Open Vault...')
    expect(sidebarFooter).not.toContain('vault-sidebar-switcher-icon')
    expect(sidebarFooter).not.toContain('vault-sidebar-open-button')
    expect(sidebarFooter).not.toContain('<strong>')
    expect(sidebarFooter).not.toContain('iconId={vault.available ?')
    const footerRule = appCss.slice(
      appCss.indexOf('.vault-sidebar-footer {'),
      appCss.indexOf('.vault-sidebar-footer.is-collapsed'),
    )
    expect(appCss).toContain('.vault-sidebar-switcher-name {\n  color: var(--app-text-heading);\n  font-weight: 400;\n}')
    expect(appCss).toContain('.vault-sidebar-footer')
    expect(footerRule).not.toContain('box-shadow')
    expect(footerRule).toContain('background: var(--vault-sidebar-bg);')
    expect(footerRule).not.toContain('background: color-mix(in srgb, var(--vault-sidebar-bg)')
    expect(appCss).toContain('.vault-sidebar-switcher-popover')
    expect(appCss).toContain('.vault-sidebar-switcher-actions')
    expect(appCss).toContain('.vault-sidebar-switcher-new')
    expect(appCss).toContain('.vault-sidebar-footer.is-collapsed')
  })

  it('uses setup-specific theme-aware startup styling', () => {
    expect(appCss).toContain('.vault-setup-brand')
    expect(appCss).toContain('.vault-setup-action-row')
    expect(appCss).toContain('.vault-setup-action-button.is-primary')
    expect(appCss).toContain('background: var(--app-page-bg)')
    expect(appCss).toContain('background: var(--app-raised)')
    expect(appCss).toContain('border: 1px solid var(--app-border-muted)')
  })

  it('keeps vault metadata readable and positions notification layers', () => {
    expect(baseCss).toContain('--ui-font-xs: calc(0.8rem * var(--app-text-scale, 1));')
    expect(appCss).toContain('.vault-manager-eyebrow,')
    expect(appCss).toContain('font-size: var(--ui-font-xs);')
    expect(appCss).not.toContain('.vault-sidebar-switcher-row-copy small')
    expect(toastsCss).toContain('.app-toast-layer')
    expect(toastsCss).toContain('right: 1rem;')
    expect(toastsCss).not.toContain('left: 1rem;')
    expect(toastsCss).toContain('.app-storage-alert-layer')
    expect(toastsCss).toContain('left: 50%;')
    expect(toastsCss).toContain('transform: translateX(-50%);')
  })

  it('subscribes to the Electron Open Vault menu navigation event', () => {
    expect(source).toContain('onOpenVaultManager?.(openVaultManagerSettings)')
    expect(source).toContain("openUtilityView('settings')")
    expect(source).toContain("setSettingsSection('data')")
    expect(source).toContain("setDataSettingsSection('storage')")
  })
})

describe('VaultApp aisle insertion focus', () => {
  it('routes shortcut and context-menu aisle creation through pending editor focus', () => {
    expect(source).toContain('addAisleFromNewlineRef.current = addAisle')
    expect(source).toContain('const insertEditorContextAisle = useCallback(')
    expect(source).toContain('addAisle(side, aisleId)')
    expect(source).toContain('pendingFocusToAisleIdRef.current = createdAisleId')
    expect(source).toContain('pendingScrollToAisleIdRef.current = createdAisleId')
    expect(source).toContain('pendingCursorRestoreRef.current = {')
    expect(source).toContain('aisleId: createdAisleId')
    expect(source).toContain("focusIntent: 'aisle-activation'")
    expect(source).toContain('setActiveAisleId(createdAisleId)')
    expect(source).not.toContain('window.setTimeout(() => setActiveAisleId(aisle.id), 0)')
  })
})
